# Generated by Django 5.2.16 on 2026-09-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('academic_term', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Institution settings',
            },
        ),
    ]
