# Generated by Django 5.2.16 on 2026-09-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsettings',
            name='assessment_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
