# Generated by Django 5.2.16 on 2026-07-19 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('band', models.CharField(max_length=40)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.CharField(choices=[('logic', 'Logical Reasoning'), ('pattern', 'Pattern Recognition'), ('decomp', 'Problem Decomposition'), ('fluency', 'Code Fluency'), ('persistence', 'Persistence'), ('attention', 'Attention to Detail')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(help_text="0-100, same scale as the mockup's indicatorsBase.score")),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'indicator_key'), name='one_score_per_student_indicator')],
            },
        ),
        migrations.CreateModel(
            name='StudentAbilityEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.CharField(choices=[('logic', 'Logical Reasoning'), ('pattern', 'Pattern Recognition'), ('decomp', 'Problem Decomposition'), ('fluency', 'Code Fluency'), ('persistence', 'Persistence'), ('attention', 'Attention to Detail')], max_length=20)),
                ('theta', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability_estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'indicator_key'), name='one_estimate_per_student_indicator')],
            },
        ),
    ]
