# Generated by Django 5.2.16 on 2026-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorscore',
            name='indicator_key',
            field=models.CharField(choices=[('math', 'Math Knowledge'), ('logic', 'Logical Reasoning'), ('algorithmic', 'Algorithmic Thinking'), ('creative', 'Creative Thinking'), ('teamwork', 'Teamwork'), ('patience', 'Patience & Persistence'), ('problem_solving', 'Problem Solving'), ('learning_speed', 'Learning Speed'), ('attention', 'Attention & Accuracy'), ('iq', 'IQ Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentabilityestimate',
            name='indicator_key',
            field=models.CharField(choices=[('math', 'Math Knowledge'), ('logic', 'Logical Reasoning'), ('algorithmic', 'Algorithmic Thinking'), ('creative', 'Creative Thinking'), ('teamwork', 'Teamwork'), ('patience', 'Patience & Persistence'), ('problem_solving', 'Problem Solving'), ('learning_speed', 'Learning Speed'), ('attention', 'Attention & Accuracy'), ('iq', 'IQ Level')], max_length=20),
        ),
    ]
