# Generated by Django 5.2.16 on 2026-07-22 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_alter_indicatorscore_indicator_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_key', models.CharField(choices=[('math', 'Math Knowledge'), ('logic', 'Logical Reasoning'), ('algorithmic', 'Algorithmic Thinking'), ('creative', 'Creative Thinking'), ('teamwork', 'Teamwork'), ('patience', 'Patience & Persistence'), ('problem_solving', 'Problem Solving'), ('learning_speed', 'Learning Speed'), ('attention', 'Attention & Accuracy'), ('iq', 'IQ Level')], max_length=20)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10)),
                ('score', models.PositiveSmallIntegerField(help_text='Indicator score at the time this tier was earned')),
                ('first_earned_at', models.DateTimeField(auto_now_add=True)),
                ('tier_earned_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'indicator_key'), name='one_achievement_per_student_indicator')],
            },
        ),
    ]
