# Generated by Django 5.2.16 on 2026-07-22 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_achievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overallscore',
            name='programming_aptitude_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FieldRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_field_key', models.CharField(blank=True, max_length=20)),
                ('fit_scores', models.JSONField(default=dict, help_text='{field_key: 0-100 fit score}, only fields that cleared the coverage gate')),
                ('completed_indicator_count', models.PositiveSmallIntegerField(default=0)),
                ('is_confident', models.BooleanField(default=False, help_text='True once completed_indicator_count >= calculators.MIN_COMPLETED_INDICATORS')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
