# Generated by Django 5.2.16 on 2026-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_overallscore_programming_aptitude_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabilityestimate',
            name='avg_response_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
