# Generated by Django 5.2.16 on 2026-08-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_studentabilityestimate_avg_response_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabilityestimate',
            name='estimation_method',
            field=models.CharField(choices=[('prior', 'Prior mean (no responses yet)'), ('eap', 'Expected a Posteriori'), ('mle', 'Maximum Likelihood (Newton-Raphson)')], default='prior', max_length=10),
        ),
        migrations.AddField(
            model_name='studentabilityestimate',
            name='se',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
