# Generated by Django 5.2.16 on 2026-09-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_valid_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
