# Generated by Django 5.2.16 on 2026-07-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('label_ru', models.CharField(max_length=60)),
                ('label_uz', models.CharField(max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'behavioral categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title_ru', models.CharField(max_length=120)),
                ('title_uz', models.CharField(max_length=120)),
                ('statement_ru', models.TextField()),
                ('statement_uz', models.TextField()),
                ('example_ru', models.TextField()),
                ('example_uz', models.TextField()),
                ('constraints_ru', models.JSONField(default=list)),
                ('constraints_uz', models.JSONField(default=list)),
                ('starter_code_ru', models.TextField()),
                ('starter_code_uz', models.TextField()),
                ('test_cases', models.JSONField(default=list, help_text='List of {"input": ..., "expected": ..., "hidden": bool, "label": str}. hidden=False cases power "Run tests"; the full list powers "Submit solution".')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CognitiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('category_ru', models.CharField(max_length=60)),
                ('category_uz', models.CharField(max_length=60)),
                ('indicator_key', models.CharField(choices=[('logic', 'Logical Reasoning'), ('pattern', 'Pattern Recognition'), ('decomp', 'Problem Decomposition'), ('fluency', 'Code Fluency'), ('persistence', 'Persistence'), ('attention', 'Attention to Detail')], max_length=20)),
                ('prompt_ru', models.TextField()),
                ('prompt_uz', models.TextField()),
                ('options_ru', models.JSONField(help_text='Ordered list of answer strings, e.g. ["36","40","42","45"]')),
                ('options_uz', models.JSONField(help_text='Same order/length as options_ru — correct_index applies to both')),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('difficulty', models.FloatField(default=0.0, help_text='IRT-style difficulty, roughly -3..3')),
            ],
            options={
                'ordering': ['indicator_key', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('cognitive', 'Cognitive'), ('coding', 'Coding'), ('behavioral', 'Behavioral')], max_length=12)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_remaining_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BehavioralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('text_ru', models.TextField()),
                ('text_uz', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('reverse_scored', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.behavioralcategory')),
            ],
            options={
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BehavioralResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_value', models.PositiveSmallIntegerField(help_text='1 (Strongly Disagree) .. 5 (Strongly Agree)')),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_responses', to='assessments.assessmentattempt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.behavioralitem')),
            ],
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('is_final', models.BooleanField(default=False)),
                ('test_results', models.JSONField(default=list)),
                ('passed_count', models.PositiveSmallIntegerField(default=0)),
                ('total_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='assessments.assessmentattempt')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.codingproblem')),
            ],
        ),
        migrations.CreateModel(
            name='CognitiveResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_responses', to='assessments.assessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.cognitivequestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('student', 'assessment_type'), name='one_attempt_per_type'),
        ),
        migrations.AddConstraint(
            model_name='behavioralresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'item'), name='one_response_per_item'),
        ),
        migrations.AddConstraint(
            model_name='cognitiveresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='one_response_per_question'),
        ),
    ]
