# Generated by Django 5.2.16 on 2026-07-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessmentattempt_assessment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cognitivequestion',
            name='correct_index',
        ),
        migrations.RemoveField(
            model_name='cognitiveresponse',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='cognitiveresponse',
            name='selected_index',
        ),
        migrations.AddField(
            model_name='cognitivequestion',
            name='correct_indices',
            field=models.JSONField(default=list, help_text='0-based option indices that count as correct. Single choice (incl. step-ordering questions folded into this type): exactly one element. Multiple choice: 2+ elements, order-independent (exact-set match). Essay: [] (unused — see apps.scoring.essay_grader).'),
        ),
        migrations.AddField(
            model_name='cognitivequestion',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single choice'), ('multi', 'Multiple choice'), ('essay', 'Essay / open-ended')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='cognitiveresponse',
            name='correctness',
            field=models.FloatField(default=0.0, help_text='0.0-1.0 fractional correctness this response contributes to the indicator average. Single/multi: 1.0 or 0.0 (exact match). Essay: rubric_scores total / 10.'),
        ),
        migrations.AddField(
            model_name='cognitiveresponse',
            name='essay_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cognitiveresponse',
            name='rubric_scores',
            field=models.JSONField(blank=True, default=dict, help_text='{"position": 2, "argument_quality": 3, "counter_argument": 1, "conclusion": 2} — keys mirror apps.reviews.models.RUBRIC_ITEMS\' stable-key convention. {} for single/multi rows.'),
        ),
        migrations.AddField(
            model_name='cognitiveresponse',
            name='selected_indices',
            field=models.JSONField(blank=True, default=list, help_text='0-based option indices the student picked. Single: 1 element. Multi: N elements. Essay: [] (unused).'),
        ),
        migrations.AlterField(
            model_name='cognitivequestion',
            name='options_ru',
            field=models.JSONField(default=list, help_text='Ordered list of answer strings, e.g. ["36","40","42","45"]. Empty for essay questions.'),
        ),
        migrations.AlterField(
            model_name='cognitivequestion',
            name='options_uz',
            field=models.JSONField(default=list, help_text='Same order/length as options_ru — correct_indices applies to both. Empty for essay questions.'),
        ),
    ]
