# Generated by Django 5.2.16 on 2026-07-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_cognitivequestion_correct_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitiveresponse',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text="Client-measured time from question display to submission. Null when the client didn't report it (older clients). Feeds AdaptiveTestingEngine's speed-aware ability update — see StudentAbilityEstimate.avg_response_ms.", null=True),
        ),
    ]
