# Generated by Django 5.2.16 on 2026-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_cognitiveresponse_response_time_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitivequestion',
            name='feedback_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cognitivequestion',
            name='feedback_uz',
            field=models.TextField(blank=True, default=''),
        ),
    ]
