# Generated by Django 5.2.16 on 2026-08-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_cognitivequestion_feedback_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitivequestion',
            name='discrimination',
            field=models.FloatField(default=1.0, help_text='2PL discrimination (a), typically 0.3..2.5; 1.0 = uncalibrated default'),
        ),
        migrations.AlterField(
            model_name='cognitivequestion',
            name='difficulty',
            field=models.FloatField(default=0.0, help_text='2PL difficulty (b), roughly -3..3'),
        ),
    ]
