# Generated by Django 5.2.16 on 2026-08-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_cognitivequestion_discrimination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='coding_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='mcq_phase_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='function_name',
            field=models.CharField(default='solution', max_length=60),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='target_time_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
