# Generated by Django 5.2.16 on 2026-08-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessmentattempt_coding_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='behavioralresponse',
            name='one_response_per_item',
        ),
        migrations.RemoveConstraint(
            model_name='cognitiveresponse',
            name='one_response_per_question',
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='attempt_cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='behavioralresponse',
            name='cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='elapsed_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cognitiveresponse',
            name='cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='behavioralresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'item', 'cycle'), name='one_response_per_item_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='cognitiveresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question', 'cycle'), name='one_response_per_question_per_cycle'),
        ),
    ]
