# Generated by Django 5.2.16 on 2026-09-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_remove_behavioralresponse_one_response_per_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
