# Generated by Django 5.2.16 on 2026-09-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_codingproblem_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('family', models.CharField(choices=[('symbols', 'Symbol language'), ('pseudocode', 'Pseudocode'), ('grammar', 'Artificial grammar')], max_length=12)),
                ('title_ru', models.CharField(max_length=120)),
                ('title_uz', models.CharField(max_length=120)),
                ('rules_ru', models.JSONField(default=list, help_text='Ordered rule lines shown on the study screen.')),
                ('rules_uz', models.JSONField(default=list)),
                ('study_seconds', models.PositiveSmallIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['family', 'key'],
            },
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='learning_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('block', models.PositiveSmallIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prompt_ru', models.TextField()),
                ('prompt_uz', models.TextField()),
                ('code', models.TextField(blank=True, default='')),
                ('options_ru', models.JSONField(default=list)),
                ('options_uz', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('explanation_ru', models.TextField(blank=True, default='')),
                ('explanation_uz', models.TextField(blank=True, default='')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.learningmodule')),
            ],
            options={
                'ordering': ['module', 'block', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_index', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_responses', to='assessments.assessmentattempt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.learningitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'item', 'cycle'), name='one_learning_response_per_item_per_cycle')],
            },
        ),
    ]
