# Generated by Django 5.2.16 on 2026-09-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_learning_speed_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='SjtScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('situation_ru', models.TextField()),
                ('situation_uz', models.TextField()),
                ('options_ru', models.JSONField(default=list)),
                ('options_uz', models.JSONField(default=list)),
                ('ratings', models.JSONField(default=list, help_text='Expert rating per option, a permutation of [1, 2, 3, 4].')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SjtResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_index', models.PositiveSmallIntegerField()),
                ('worst_index', models.PositiveSmallIntegerField()),
                ('points', models.FloatField(help_text='-2..2 — see state_tracker.sjt_points.')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sjt_responses', to='assessments.assessmentattempt')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.sjtscenario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'scenario', 'cycle'), name='one_sjt_response_per_scenario_per_cycle')],
            },
        ),
    ]
