# Generated by Django 5.2.16 on 2026-09-18 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_teamwork_sjt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek')], max_length=2)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('unsolvable', 'Unsolvable')], max_length=10)),
                ('letters', models.CharField(help_text='Uppercase letters to rearrange (shuffled again when served).', max_length=20)),
                ('answers', models.JSONField(blank=True, default=list, help_text='Accepted uppercase words; empty = unsolvable.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['language', 'difficulty', 'key'],
            },
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='anagram_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AnagramResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('guesses', models.JSONField(default=list, help_text='Distinct wrong guesses, in order.')),
                ('active_ms', models.PositiveIntegerField(default=0, help_text='Client-measured time the student was actually working on this item (tab visible, recent input).')),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anagram_responses', to='assessments.assessmentattempt')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.anagramitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'item', 'cycle'), name='one_anagram_response_per_item_per_cycle')],
            },
        ),
    ]
