# Generated by Django 5.2.16 on 2026-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_patience_anagrams'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='config_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
