"""
Seed content for the teamwork situational judgment test (SjtScenario).

Every option is written to sound reasonable; the weakest ones typically look
helpful or polite but hide the problem, remove a teammate's ownership, or dodge
the conflict. Each option is (text_uz, text_ru, expert_rating) with ratings
4 = most effective … 1 = least effective. Options are shuffled per student at
serve time, so authoring order doesn't matter.
"""


def _s(n, situation_uz, situation_ru, options):
    assert sorted(r for _, _, r in options) == [1, 2, 3, 4], n
    return {
        'key': f'teamwork-sjt-{n}',
        'situation_uz': situation_uz, 'situation_ru': situation_ru,
        'options_uz': [uz for uz, _, _ in options],
        'options_ru': [ru for _, ru, _ in options],
        'ratings': [r for _, _, r in options],
    }


SJT_SCENARIOS = [
    _s(1, "Guruh loyihasida bir jamoadosh ikki haftadan beri o'z qismini topshirmayapti. Muddatga 5 kun qoldi.",
       'В групповом проекте один из участников уже две недели не сдаёт свою часть. До дедлайна 5 дней.', [
           ("Uning qismini boshqa a'zolar o'rtasida qayta taqsimlashni taklif qilasiz, unga kichikroq qism qoldirasiz.",
            'Предложить перераспределить его часть между остальными, оставив ему меньший объём.', 2),
           ('U bilan alohida gaplashib, sababini bilasiz va shunga qarab jamoa bilan yechim topasiz.',
            'Поговорить с ним наедине, выяснить причину и вместе с командой найти решение.', 4),
           ("Yig'ilishda har bir a'zodan o'z qismining holatini qisqacha aytib berishni so'raysiz.",
            'На встрече попросить каждого кратко рассказать о статусе своей части.', 3),
           ("Vaqt ketmasligi uchun uning qismini o'zingiz boshlab qo'yasiz, keyin unga tekshirishga berasiz.",
            'Чтобы не терять время, самому начать его часть, а потом отдать ему на проверку.', 1),
       ]),
    _s(2, "Jamoa ovoz berish arafasida. Ko'pchilik sizningcha zaifroq bo'lgan variantga moyil.",
       'Команда вот-вот проголосует. Большинство склоняется к варианту, который вам кажется более слабым.', [
           ("Ko'pchilikka qo'shilasiz, chunki jamoa birligi bitta to'g'ri yechimdan muhimroq.",
            'Присоединиться к большинству: единство команды важнее одного верного решения.', 1),
           ("Tanlangan variant bo'yicha ishlaysiz, uning xavfli tomonlarini esa alohida yozib qo'yasiz.",
            'Работать по выбранному варианту, а его риски отдельно записать.', 2),
           ("Ovozdan oldin ikkala variantni bir xil mezonlar bo'yicha solishtirib chiqishni taklif qilasiz.",
            'До голосования предложить сравнить оба варианта по одинаковым критериям.', 4),
           ('Ikkala variantni birlashtirgan murosa yechim taklif qilasiz.',
            'Предложить компромисс, объединяющий оба варианта.', 3),
       ]),
    _s(3, "Ikki jamoadosh bitta vazifani kim bajarishi ustida tortishib qolgan, ish to'xtab turibdi.",
       'Двое участников спорят, кто будет делать одну и ту же задачу, и работа стоит.', [
           ("Ikkalasini alohida tinglab, keyin o'z yechimingizni taklif qilasiz.",
            'Выслушать обоих по отдельности, а затем предложить своё решение.', 3),
           ("Tortishuv keskinlashmasligi uchun o'sha vazifani vaqtincha o'zingiz olasiz.",
            'Чтобы спор не обострился, временно взять эту задачу себе.', 1),
           ("Suhbatni «loyiha natijasi uchun qaysi taqsimot yaxshiroq?» degan savolga burasiz.",
            'Перевести разговор на вопрос «какое распределение лучше для результата проекта?».', 4),
           ("Sardor yoki o'qituvchidan vazifani biriktirib berishni so'raysiz.",
            'Попросить лидера или преподавателя закрепить задачу за кем-то.', 2),
       ]),
    _s(4, "Topshirishdan bir kun oldin jamoadoshingiz qismida jiddiy xato ko'rdingiz. U tanqidni og'ir qabul qiladi.",
       'За день до сдачи вы нашли серьёзную ошибку в части коллеги. Коллега болезненно воспринимает критику.', [
           ("Unga shaxsan yozib, xato qayerdaligini ko'rsatasiz va birga tuzatishni taklif qilasiz.",
            'Написать коллеге лично, показать, где ошибка, и предложить исправить вместе.', 4),
           ("Yig'ilishda «hamma qismni birga tekshirib chiqaylik» deysiz, xato shu jarayonda o'zi chiqadi.",
            'На встрече предложить «давайте вместе проверим все части» — ошибка всплывёт сама.', 3),
           ('Xatoni sardorga aytasiz, qanday yetkazishni u hal qilsin.',
            'Сообщить об ошибке лидеру — пусть он решит, как её донести.', 2),
           ("Uning ko'ngli qolmasligi uchun xatoni o'zingiz jimgina tuzatib qo'yasiz.",
            'Чтобы не задеть коллегу, тихо исправить ошибку самому.', 1),
       ]),
    _s(5, "Loyiha o'rtasida jamoaga yangi a'zo qo'shildi va u hali hech narsani tushunmayapti. Siz ham ancha bandsiz.",
       'В середине проекта в команду пришёл новый участник, который пока ничего не понимает. Вы тоже сильно загружены.', [
           ("Unga hozircha mustaqil bajarsa bo'ladigan oddiyroq vazifalarni berasiz.",
            'Дать ему пока простые задачи, которые можно сделать самостоятельно.', 2),
           ('15 daqiqa ajratib, loyiha holatini tushuntirasiz va unga aniq bitta vazifa berasiz.',
            'Выделить 15 минут, объяснить состояние проекта и дать ему одну конкретную задачу.', 4),
           ("Loyiha hujjatlari va chat tarixini yuborib, savollari bo'lsa yozishini aytasiz.",
            'Отправить документацию и историю чата и сказать, чтобы писал, если будут вопросы.', 3),
           ("Muddat yaqin bo'lgani uchun uni hozircha jalb qilmay, keyingi bosqichda qo'shasiz.",
            'Раз дедлайн близко, пока не подключать его и привлечь на следующем этапе.', 1),
       ]),
    _s(6, "Siz jamoa sardorisiz. Bir a'zo yig'ilishlarda doim jim o'tiradi, lekin ishini vaqtida bajaradi.",
       'Вы лидер команды. Один участник на встречах всегда молчит, но работу сдаёт вовремя.', [
           ('Ishi yaxshi ekan, uning uslubiga aralashmaysiz.',
            'Раз работа в порядке, не вмешиваться в его стиль.', 2),
           ("Yig'ilishlarda navbat bilan har kimdan fikr so'rash tartibini joriy qilasiz.",
            'Ввести на встречах порядок, при котором мнение спрашивают у каждого по очереди.', 4),
           ("Yig'ilishdan keyin undan alohida fikrini so'rab turasiz.",
            'После встреч отдельно спрашивать его мнение.', 3),
           ("Unga faolroq bo'lishi kerakligini ochiq aytasiz.",
            'Прямо сказать ему, что нужно быть активнее.', 1),
       ]),
    _s(7, "Jamoa bitta branchda ishlayapti va a'zolar tez-tez bir-birining kodini buzib qo'yyapti.",
       'Команда работает в одной ветке, и участники постоянно ломают код друг друга.', [
           ("Har kim o'z qismini alohida yozib, oxirida hammasini birlashtirishni taklif qilasiz.",
            'Предложить, чтобы каждый писал свою часть отдельно, а в конце всё объединить.', 2),
           ('Jamoa bilan qisqa kelishuv tuzasiz: branch va code review tartibi, kim nima uchun javobgar.',
            'Договориться с командой о коротких правилах: ветки, code review, кто за что отвечает.', 4),
           ("Kim ko'proq buzayotganini aniqlab, u bilan alohida gaplashasiz.",
            'Выяснить, кто ломает чаще всего, и поговорить с ним отдельно.', 1),
           ("Kodni birlashtirish va oxirgi tekshiruvni o'z zimmangizga olasiz.",
            'Взять на себя объединение кода и финальную проверку.', 3),
       ]),
    _s(8, "Siz yo'l qo'ygan xato tufayli jamoa muddatdan kechikishi mumkin. Buni hali hech kim sezmagan.",
       'Из-за вашей ошибки команда может не успеть к сроку. Пока этого никто не заметил.', [
           ('Jamoaga hoziroq xabar berib, tuzatish rejasini ham taklif qilasiz.',
            'Сразу сообщить команде и предложить план исправления.', 4),
           ('Tunda ishlab, hech kimga aytmasdan xatoni tuzatishga harakat qilasiz.',
            'Поработать ночью и постараться исправить ошибку, никому не говоря.', 1),
           ("Avval o'zingiz tuzatishga urinib, uddalay olmasangiz jamoaga aytasiz.",
            'Сначала попробовать исправить самому, а если не получится — сказать команде.', 2),
           ('Sardorga aytasiz va jamoaga qanday yetkazishni u bilan kelishasiz.',
            'Сказать лидеру и вместе решить, как сообщить команде.', 3),
       ]),
    _s(9, "Jamoadoshingiz sizning g'oyangizni o'qituvchi oldida o'zinikidek taqdim etdi.",
       'Коллега представил вашу идею преподавателю как свою.', [
           ("O'qituvchi oldida g'oya sizniki ekanini aytib, aniqlik kiritasiz.",
            'Прямо при преподавателе уточнить, что идея ваша.', 2),
           ("Keyin u bilan alohida gaplashib, bu sizga qanday ta'sir qilganini aytasiz.",
            'Позже поговорить с ним наедине и сказать, как это на вас повлияло.', 4),
           ("Hech narsa demaysiz — asosiysi, jamoaning umumiy natijasi.",
            'Ничего не говорить — главное общий результат команды.', 1),
           ("Bundan keyin g'oyalaringizni avval jamoa chatiga yozib qo'yasiz, muallifi ko'rinib tursin.",
            'Впредь сначала писать свои идеи в общий чат, чтобы было видно авторство.', 3),
       ]),
    _s(10, 'Hakaton tugashiga 3 soat qoldi. Jamoa ikki xil texnologiyadan qaysi birini tanlash ustida bahslashmoqda.',
       'До конца хакатона 3 часа. Команда спорит, какую из двух технологий выбрать.', [
           ("Eng tajribali a'zo qaror qabul qilsin, deb taklif qilasiz.",
            'Предложить, чтобы решение принял самый опытный участник.', 3),
           ("10 daqiqa belgilab, har bir variant bo'yicha qisqa dalillarni eshitib, keyin qaror qilishni taklif qilasiz.",
            'Предложить 10 минут на короткие аргументы за каждый вариант, а затем решить.', 4),
           ('Vaqtni tejash uchun ikkala variant ustida parallel ishlashni taklif qilasiz.',
            'Чтобы сэкономить время, предложить параллельно работать над обоими вариантами.', 2),
           ("O'zingiz yaxshi biladigan variantni tanlab, ishni boshlab yuborasiz.",
            'Выбрать вариант, который вы знаете лучше, и начать работу.', 1),
       ]),
    _s(11, "Jamoadoshingiz so'nggi haftalarda juda charchagan va asabiy ko'rinadi, ishining sifati pasaygan.",
       'Коллега в последние недели выглядит уставшим и раздражённым, качество его работы снизилось.', [
           ("Undan alohida ahvolini so'rab, yuklamani kamaytirish kerakmi, deb qiziqasiz.",
            'Отдельно спросить, как у него дела, и не нужно ли снизить нагрузку.', 4),
           ("Yig'ilishda hech kimni nomlamasdan, ish sifati haqida umumiy eslatma berasiz.",
            'На встрече, никого не называя, сделать общее напоминание о качестве работы.', 1),
           ('Uning vazifalarining bir qismini jimgina o\'zingizga olasiz.',
            'Тихо взять часть его задач на себя.', 2),
           ("Unga sifat pasayganini aniq misollar bilan aytib, yaxshilashni so'raysiz.",
            'Сказать ему на конкретных примерах, что качество снизилось, и попросить улучшить.', 3),
       ]),
    _s(12, "Jamoa qaror qabul qilib, uni e'lon ham qildi. Siz bu qarorda muhim bir xavfni ko'ryapsiz.",
       'Команда приняла решение и уже объявила его. Вы видите в нём серьёзный риск.', [
           ("Qarorni qo'llab-quvvatlaysiz, xavf haqida esa u yuzaga chiqsa aytasiz.",
            'Поддержать решение, а о риске сказать, если он проявится.', 1),
           ('Xavfni aniq faktlar bilan jamoaga yozib, uni kamaytirish yo\'lini ham taklif qilasiz.',
            'Написать команде о риске с конкретными фактами и предложить, как его снизить.', 4),
           ("Qarorni qayta ko'rib chiqish uchun yangi ovoz berishni talab qilasiz.",
            'Потребовать нового голосования, чтобы пересмотреть решение.', 2),
           ("Jamoani chalg'itmaslik uchun xavfni faqat sardorga aytasiz.",
            'Чтобы не сбивать команду, сказать о риске только лидеру.', 3),
       ]),
    _s(13, "Jamoadagi bir a'zo boshqalarning gapini tez-tez bo'lib, o'z fikrini o'tkazadi.",
       'Один участник часто перебивает других и продавливает своё мнение.', [
           ("U gapni bo'lganda, «keling, avval fikrni oxirigacha eshitaylik» deb so'zni qaytarasiz.",
            'Когда он перебивает, мягко вернуть слово: «давайте сначала дослушаем».', 4),
           ("Yig'ilishdan keyin u bilan alohida gaplashib, buni o'zi sezadimi, deb so'raysiz.",
            'После встречи поговорить с ним наедине и спросить, замечает ли он это.', 3),
           ("Boshqalar bunga ko'nikib qolgani uchun vaziyatni o'z holiga qo'yasiz.",
            'Раз остальные уже привыкли, оставить всё как есть.', 1),
           ("Hamma uchun «gapni bo'lmaslik» qoidasini yozib qo'yishni taklif qilasiz.",
            'Предложить записать для всех правило «не перебивать».', 2),
       ]),
    _s(14, "O'qituvchi jamoaga qo'shimcha topshiriq berdi. Hamma band va hech kim uni olishni xohlamayapti.",
       'Преподаватель дал команде дополнительное задание. Все заняты, и никто не хочет его брать.', [
           ("Kimdir ixtiyoriy chiqishini kutasiz — majburan qilingan ish sifatli bo'lmaydi.",
            'Подождать, пока кто-то вызовется сам, — работа из-под палки не бывает качественной.', 1),
           ("Topshiriqni kichik qismlarga bo'lib, hammaga teng taqsimlashni taklif qilasiz.",
            'Предложить разбить задание на части и распределить поровну.', 4),
           ("O'zingiz olasiz va keyingi safar navbat boshqaga o'tishini kelishib olasiz.",
            'Взять его себе и договориться, что в следующий раз очередь за другим.', 3),
           ("O'qituvchiga jamoa bandligini aytib, muddatni uzaytirishni so'raysiz.",
            'Сказать преподавателю, что команда загружена, и попросить продлить срок.', 2),
       ]),
    _s(15, "Siz jamoadagi eng kuchli dasturchisiz. Bir a'zo sekin ishlaydi va sizga tez-tez savol beradi.",
       'Вы самый сильный программист в команде. Один участник работает медленно и часто задаёт вам вопросы.', [
           ("Savollariga javob berish o'rniga, kerakli qismni o'zingiz tezda yozib berasiz.",
            'Вместо ответов на вопросы быстро написать нужную часть за него.', 1),
           ("Kuniga bir marta qisqa vaqt ajratib, savollarini birga ko'rib chiqasiz.",
            'Раз в день выделять немного времени и разбирать его вопросы вместе.', 4),
           ("Unga foydali materiallar yuborib, avval o'zi urinib ko'rishini so'raysiz.",
            'Отправить полезные материалы и попросить сначала попробовать самому.', 3),
           ("Sardorga unga murakkab bo'lmagan vazifalar berishni taklif qilasiz.",
            'Предложить лидеру давать ему задачи попроще.', 2),
       ]),
    _s(16, "Jamoa loyihasiga umumiy baho qo'yiladi, lekin bir a'zo deyarli hech narsa qilmadi. O'qituvchi har kimning hissasi haqida so'radi.",
       'За командный проект ставится общая оценка, но один участник почти ничего не сделал. Преподаватель спрашивает о вкладе каждого.', [
           ("Hamma teng ishladi, deysiz — jamoadoshni sotib qo'ymaslik kerak.",
            'Сказать, что все работали одинаково, — своих не сдают.', 1),
           ("Har bir a'zo qilgan ishni faktlar asosida xolis aytib berasiz.",
            'Объективно, на фактах рассказать, что сделал каждый.', 4),
           ("Faqat o'z hissangiz haqida gapirasiz, boshqalarga baho bermaysiz.",
            'Рассказать только о своём вкладе, не оценивая других.', 2),
           ("Avval o'sha a'zo bilan gaplashib, o'qituvchiga nima deyishni birga kelishib olasiz.",
            'Сначала поговорить с этим участником и вместе решить, что сказать преподавателю.', 3),
       ]),
    _s(17, "A'zolar turli vaqtda ishlaydi va chatdagi muhim qarorlar boshqa xabarlar orasida yo'qolib ketyapti.",
       'Участники работают в разное время, и важные решения теряются среди сообщений в чате.', [
           ("Muhim qarorlarni alohida hujjatga yozib borishni taklif qilasiz va birinchisini o'zingiz yozasiz.",
            'Предложить фиксировать важные решения в отдельном документе и сделать первую запись самому.', 4),
           ("Har kuni ma'lum soatda hamma onlayn bo'lishini talab qilasiz.",
            'Потребовать, чтобы каждый день в определённый час все были онлайн.', 2),
           ("Qarorni o'tkazib yuborgan a'zo chat tarixini o'zi o'qishi kerak, deb hisoblaysiz.",
            'Считать, что пропустивший решение должен сам читать историю чата.', 1),
           ("Har hafta qisqa qo'ng'iroqda asosiy qarorlarni takrorlashni taklif qilasiz.",
            'Предложить раз в неделю коротко проговаривать главные решения на созвоне.', 3),
       ]),
    _s(18, "Jamoadoshingiz siz yozgan kod haqida keskin ohangda, lekin asosli izohlar qoldirdi.",
       'Коллега оставил к вашему коду резкие по тону, но обоснованные замечания.', [
           ("Izohlarning mazmuniga javob berasiz, ohang haqida esa keyin alohida gaplashasiz.",
            'Ответить по существу замечаний, а о тоне поговорить потом отдельно.', 4),
           ("Kelishmovchilik chiqmasligi uchun barcha izohlarni indamay tuzatib qo'yasiz.",
            'Чтобы не было конфликта, молча исправить всё по замечаниям.', 3),
           ("Avval izohlarni hurmat bilan yozishini so'raysiz, keyin tuzatasiz.",
            'Сначала попросить писать замечания уважительно, а потом исправить.', 2),
           ("Uning kodini ham xuddi shunday sinchkovlik bilan ko'rib chiqib, izohlar qoldirasiz.",
            'Так же придирчиво просмотреть его код и оставить замечания.', 1),
       ]),
    _s(19, "Siz vazifalarni taqsimladingiz, lekin bir a'zo o'ziga berilgan vazifa qiziq emasligini aytdi.",
       'Вы распределили задачи, но один участник говорит, что его задача ему неинтересна.', [
           ("Vazifalar hamma uchun adolatli bo'lishi kerakligini tushuntirib, taqsimotni o'zgartirmaysiz.",
            'Объяснить, что распределение должно быть справедливым для всех, и ничего не менять.', 2),
           ("Qaysi vazifa unga qiziqligini so'rab, jamoa bilan almashtirish mumkinligini ko'rib chiqasiz.",
            'Спросить, какая задача ему интересна, и обсудить с командой возможность обмена.', 4),
           ("Unga yoqadigan vazifani darhol berib, uning vazifasini o'zingiz olasiz.",
            'Сразу отдать ему интересную задачу, а его задачу взять себе.', 1),
           ("Hozircha shu vazifani bajarishini, keyingi taqsimotda xohishi hisobga olinishini aytasiz.",
            'Попросить пока выполнить эту задачу и пообещать учесть его пожелания при следующем распределении.', 3),
       ]),
    _s(20, "Jamoa loyihasi himoyasida bir a'zo komissiya savoliga javob bera olmay qoldi.",
       'На защите командного проекта один участник не может ответить на вопрос комиссии.', [
           ("Suhbatga qo'shilib, uning fikrini davom ettirishga yordam berasiz.",
            'Подключиться и помочь ему развить его мысль.', 4),
           ("Vaqt ketmasligi uchun savolga o'zingiz to'liq javob berasiz.",
            'Чтобы не терять время, полностью ответить на вопрос самому.', 2),
           ("Uning o'zi uddalashiga imkon berib, aralashmaysiz.",
            'Не вмешиваться, дать ему справиться самому.', 1),
           ("Himoyadan keyin unga qanday tayyorlanish kerakligini tushuntirasiz.",
            'После защиты объяснить ему, как нужно было подготовиться.', 3),
       ]),
]
