"""
Seed content for the teamwork situational judgment test (SjtScenario) —
100 scenarios, grouped by theme: coordination and process, conflict and
disagreement, accountability, communication and feedback, mentoring,
leadership and decisions, fairness and integrity, pressure and change.

Every option is written to sound reasonable; the weakest ones typically look
helpful or polite but hide the problem, remove a teammate's ownership, or dodge
the conflict. Each option is (text_uz, text_ru, expert_rating) with ratings
4 = most effective … 1 = least effective. Options are shuffled per student at
serve time, so authoring order doesn't matter.

Authoring rule — the best option must not be guessable from its surface form:
keep the four options within roughly 10-15 characters of each other in BOTH
languages, and rotate which rating happens to be the longest. Across the pool
the 4-rated option's average length rank is ~2.4/4 (i.e. no length cue); an
earlier draft sat at 1.5, where "pick the longest" would have been a winning
strategy. Vary the shape of the best answer too (talk to the person, fix the
process, raise it with the whole team, hand ownership back) so that no single
phrasing pattern marks the key.
"""


def _s(n, situation_uz, situation_ru, options):
    assert sorted(r for _, _, r in options) == [1, 2, 3, 4], n
    return {
        'key': f'teamwork-sjt-{n}',
        'situation_uz': situation_uz, 'situation_ru': situation_ru,
        'options_uz': [uz for uz, _, _ in options],
        'options_ru': [ru for _, ru, _ in options],
        'ratings': [r for _, _, r in options],
    }


SJT_SCENARIOS = [
    _s(1, "Guruh loyihasida bir jamoadosh ikki haftadan beri o'z qismini topshirmayapti. Muddatga 5 kun qoldi.",
       'В групповом проекте один из участников уже две недели не сдаёт свою часть. До дедлайна 5 дней.', [
           ("Uning qismini boshqa a'zolar o'rtasida qayta taqsimlashni taklif qilasiz, unga kichikroq qism qoldirasiz.",
            'Предложить перераспределить его часть между остальными, оставив ему меньший объём.', 2),
           ('U bilan alohida gaplashib, sababini bilasiz va shunga qarab jamoa bilan yechim topasiz.',
            'Поговорить с ним наедине, выяснить причину и вместе с командой найти решение.', 4),
           ("Yig'ilishda har bir a'zodan o'z qismining holatini qisqacha aytib berishni so'raysiz.",
            'На встрече попросить каждого кратко рассказать о статусе своей части.', 3),
           ("Vaqt ketmasligi uchun uning qismini o'zingiz boshlab qo'yasiz, keyin unga tekshirishga berasiz.",
            'Чтобы не терять время, самому начать его часть, а потом отдать ему на проверку.', 1),
       ]),
    _s(2, "Jamoa ovoz berish arafasida. Ko'pchilik sizningcha zaifroq bo'lgan variantga moyil.",
       'Команда вот-вот проголосует. Большинство склоняется к варианту, который вам кажется более слабым.', [
           ("Ko'pchilikka qo'shilasiz, chunki jamoa birligi bitta to'g'ri yechimdan muhimroq.",
            'Присоединиться к большинству: единство команды важнее одного верного решения.', 1),
           ("Tanlangan variant bo'yicha ishlashda davom etasiz, uning xavfli tomonlarini esa alohida yozib qo'yasiz.",
            'Продолжать работать по выбранному варианту, а его риски отдельно записать.', 2),
           ("Ovozdan oldin ikkala variantni bir xil mezonlar bo'yicha solishtirib chiqishni taklif qilasiz.",
            'До голосования предложить сравнить оба варианта по одинаковым критериям.', 4),
           ('Ikkala variantni birlashtirgan murosa yechim taklif qilasiz.',
            'Предложить компромисс, объединяющий оба варианта.', 3),
       ]),
    _s(3, "Ikki jamoadosh bitta vazifani kim bajarishi ustida tortishib qolgan, ish to'xtab turibdi.",
       'Двое участников спорят, кто будет делать одну и ту же задачу, и работа стоит.', [
           ("Ikkalasini alohida tinglab, keyin o'z yechimingizni taklif qilasiz.",
            'Выслушать обоих по отдельности, а затем предложить своё решение.', 3),
           ("Tortishuv yanada keskinlashib ketmasligi uchun o'sha vazifani vaqtincha o'zingiz olasiz.",
            'Чтобы спор не обострился ещё сильнее, на время взять эту задачу себе и не мешать им.', 1),
           ("Suhbatni «loyiha natijasi uchun qaysi taqsimot yaxshiroq?» degan savolga burasiz.",
            'Перевести разговор на вопрос «какое распределение лучше для результата проекта?».', 4),
           ("Sardor yoki o'qituvchidan vazifani biriktirib berishni so'raysiz.",
            'Попросить лидера или преподавателя закрепить задачу за кем-то.', 2),
       ]),
    _s(4, "Topshirishdan bir kun oldin jamoadoshingiz qismida jiddiy xato ko'rdingiz. U tanqidni og'ir qabul qiladi.",
       'За день до сдачи вы нашли серьёзную ошибку в части коллеги. Коллега болезненно воспринимает критику.', [
           ("Unga shaxsan yozib, xato qayerdaligini ko'rsatasiz va birga tuzatishni taklif qilasiz.",
            'Написать коллеге лично, показать, где ошибка, и предложить исправить вместе.', 4),
           ("Yig'ilishda «hamma qismni birga tekshirib chiqaylik» deysiz, xato shu jarayonda o'zi chiqadi.",
            'На встрече предложить «давайте вместе проверим все части» — ошибка всплывёт сама.', 3),
           ('Xatoni sardorga aytasiz, qanday yetkazishni u hal qilsin.',
            'Сообщить об ошибке лидеру — пусть он решит, как её донести.', 2),
           ("Uning ko'ngli qolmasligi uchun xatoni o'zingiz jimgina tuzatib qo'yasiz.",
            'Чтобы не задеть коллегу, тихо исправить ошибку самому.', 1),
       ]),
    _s(5, "Loyiha o'rtasida jamoaga yangi a'zo qo'shildi va u hali hech narsani tushunmayapti. Siz ham ancha bandsiz.",
       'В середине проекта в команду пришёл новый участник, который пока ничего не понимает. Вы тоже сильно загружены.', [
           ("Unga hozircha mustaqil bajarsa bo'ladigan oddiyroq vazifalarni berasiz.",
            'Дать ему пока простые задачи, которые можно сделать самостоятельно.', 2),
           ('15 daqiqa ajratib, loyiha holatini tushuntirasiz va unga aniq bitta vazifa berasiz.',
            'Выделить 15 минут, объяснить состояние проекта и дать ему одну конкретную задачу.', 4),
           ("Loyiha hujjatlari va chat tarixini yuborib, savollari bo'lsa yozishini aytasiz.",
            'Отправить документацию и историю чата и сказать, чтобы писал, если будут вопросы.', 3),
           ("Muddat yaqin bo'lgani uchun uni hozircha jalb qilmay, keyingi bosqichda qo'shib olasiz.",
            'Раз дедлайн уже близко, пока не подключать его и привлечь только на следующем этапе.', 1),
       ]),
    _s(6, "Siz jamoa sardorisiz. Bir a'zo yig'ilishlarda doim jim o'tiradi, lekin ishini vaqtida bajaradi.",
       'Вы лидер команды. Один участник на встречах всегда молчит, но работу сдаёт вовремя.', [
           ("Ishi yaxshi ekan, uning yig'ilishdagi uslubiga aralashmaysiz.",
            'Раз работа в порядке, не вмешиваться в его манеру на встречах.', 2),
           ("Yig'ilishlarda navbat bilan har kimdan fikr so'rash tartibini joriy qilasiz.",
            'Ввести на встречах порядок, при котором мнение спрашивают у каждого по очереди.', 4),
           ("Har bir yig'ilishdan keyin undan alohida qanday fikrda ekanini so'rab turasiz.",
            'После каждой встречи отдельно спрашивать у него, что он обо всём этом думает сам.', 3),
           ("Unga yig'ilishlarda faolroq bo'lishi kerakligini ochiq aytasiz.",
            'Прямо сказать ему, что на встречах нужно быть активнее.', 1),
       ]),
    _s(7, "Jamoa bitta branchda ishlayapti va a'zolar tez-tez bir-birining kodini buzib qo'yyapti.",
       'Команда работает в одной ветке, и участники постоянно ломают код друг друга.', [
           ("Har kim o'z qismini alohida yozib chiqsin, oxirida esa hammasini birlashtirishni taklif qilasiz.",
            'Предложить, чтобы каждый писал свою часть отдельно, а уже в самом конце всё это объединить.', 2),
           ('Jamoa bilan qisqa kelishuv tuzasiz: branch va code review tartibi, kim nima uchun javobgar.',
            'Договориться с командой о коротких правилах: ветки, code review, кто за что отвечает.', 4),
           ("Kim ko'proq buzayotganini aniqlab, u bilan alohida gaplashasiz.",
            'Выяснить, кто ломает чаще всего, и поговорить с ним отдельно.', 1),
           ("Kodni birlashtirish va oxirgi tekshiruvni o'z zimmangizga olasiz.",
            'Взять на себя объединение кода и финальную проверку.', 3),
       ]),
    _s(8, "Siz yo'l qo'ygan xato tufayli jamoa muddatdan kechikishi mumkin. Buni hali hech kim sezmagan.",
       'Из-за вашей ошибки команда может не успеть к сроку. Пока этого никто не заметил.', [
           ('Jamoaga hoziroq xabar berib, tuzatish rejasini ham taklif qilasiz.',
            'Сразу сообщить команде и предложить план исправления.', 4),
           ('Tunda ishlab, hech kimga aytmasdan xatoni tuzatishga harakat qilasiz.',
            'Поработать ночью и постараться исправить ошибку, никому не говоря.', 1),
           ("Avval o'zingiz tuzatishga urinib, uddalay olmasangiz jamoaga aytasiz.",
            'Сначала попробовать исправить самому, а если не получится — сказать команде.', 2),
           ('Sardorga aytasiz va jamoaga qanday yetkazishni u bilan kelishasiz.',
            'Сказать лидеру и вместе решить, как сообщить команде.', 3),
       ]),
    _s(9, "Jamoadoshingiz sizning g'oyangizni o'qituvchi oldida o'zinikidek taqdim etdi.",
       'Коллега представил вашу идею преподавателю как свою.', [
           ("O'qituvchi oldida g'oya sizniki ekanini aytib, aniqlik kiritasiz.",
            'Прямо при преподавателе уточнить, что идея ваша.', 2),
           ("Keyin u bilan alohida gaplashib, bu sizga qanday ta'sir qilganini aytasiz.",
            'Позже поговорить с ним наедине и сказать, как это на вас повлияло.', 4),
           ("Hech narsa demaysiz — asosiysi, jamoaning umumiy natijasi.",
            'Ничего не говорить — главное общий результат команды.', 1),
           ("Bundan keyin g'oyalaringizni avval jamoa chatiga yozib qo'yasiz, muallifi ko'rinib tursin.",
            'Впредь сначала писать свои идеи в общий чат, чтобы было видно авторство.', 3),
       ]),
    _s(10, 'Hakaton tugashiga 3 soat qoldi. Jamoa ikki xil texnologiyadan qaysi birini tanlash ustida bahslashmoqda.',
       'До конца хакатона 3 часа. Команда спорит, какую из двух технологий выбрать.', [
           ("Eng tajribali a'zo qaror qabul qilsin, deb taklif qilib ko'rasiz.",
            'Предложить, чтобы решение принял самый опытный участник команды.', 3),
           ("10 daqiqa ajratib, har bir variant bo'yicha qisqa dalillarni eshitib, qaror qilasiz.",
            'Предложить 10 минут на короткие аргументы за каждый вариант, а затем решить.', 4),
           ('Vaqtni tejash uchun ikkala variant ustida bir vaqtda parallel ishlashni taklif qilasiz.',
            'Чтобы сэкономить время, предложить работать над обоими вариантами параллельно.', 2),
           ("O'zingiz yaxshi biladigan variantni tanlab, darhol ishni boshlab yuborasiz.",
            'Выбрать вариант, который вы знаете лучше, и сразу начать работу.', 1),
       ]),
    _s(11, "Jamoadoshingiz so'nggi haftalarda juda charchagan va asabiy ko'rinadi, ishining sifati pasaygan.",
       'Коллега в последние недели выглядит уставшим и раздражённым, качество его работы снизилось.', [
           ("Undan alohida ahvolini so'rab, yuklamani kamaytirish kerakmi, deb qiziqasiz.",
            'Отдельно спросить, как у него дела, и не нужно ли снизить нагрузку.', 4),
           ("Yig'ilishda hech kimni nomlamasdan, ish sifati haqida umumiy eslatma berasiz.",
            'На встрече, никого не называя, сделать общее напоминание о качестве работы.', 1),
           ('Uning vazifalarining bir qismini jimgina o\'zingizga olasiz.',
            'Тихо взять часть его задач на себя.', 2),
           ("Unga sifat pasayganini aniq misollar bilan aytib, yaxshilashni so'raysiz.",
            'Сказать ему на конкретных примерах, что качество снизилось, и попросить улучшить.', 3),
       ]),
    _s(12, "Jamoa qaror qabul qilib, uni e'lon ham qildi. Siz bu qarorda muhim bir xavfni ko'ryapsiz.",
       'Команда приняла решение и уже объявила его. Вы видите в нём серьёзный риск.', [
           ("Qarorni qo'llab-quvvatlaysiz, xavf haqida esa u yuzaga chiqqanda aytasiz.",
            'Поддержать решение, а о риске сказать, когда он проявится.', 1),
           ('Xavfni aniq faktlar bilan jamoaga yozib, uni kamaytirish yo\'lini ham taklif qilasiz.',
            'Написать команде о риске с конкретными фактами и предложить, как его снизить.', 4),
           ("Qabul qilingan qarorni qayta ko'rib chiqish uchun yangidan ovoz berishni talab qilasiz.",
            'Потребовать провести новое голосование, чтобы пересмотреть уже принятое решение.', 2),
           ("Jamoani chalg'itmaslik uchun xavf haqida faqat sardorga aytasiz.",
            'Чтобы не сбивать команду, сказать о риске только лидеру проекта.', 3),
       ]),
    _s(13, "Jamoadagi bir a'zo boshqalarning gapini tez-tez bo'lib, o'z fikrini o'tkazadi.",
       'Один участник часто перебивает других и продавливает своё мнение.', [
           ("U gapni bo'lganda, «keling, avval fikrni oxirigacha eshitaylik» deb so'zni qaytarasiz.",
            'Когда он перебивает, мягко вернуть слово: «давайте сначала дослушаем».', 4),
           ("Yig'ilishdan keyin u bilan alohida gaplashib, buni o'zi sezadimi-yo'qmi, deb so'raysiz.",
            'После встречи поговорить с ним наедине и спросить, замечает ли он это за собой.', 3),
           ("Boshqalar bunga ko'nikib qolgani uchun vaziyatni o'z holiga qo'yasiz.",
            'Раз остальные уже привыкли, оставить всё как есть.', 1),
           ("Hamma uchun «gapni bo'lmaslik» qoidasini yozib qo'yishni taklif qilasiz.",
            'Предложить записать для всех правило «не перебивать».', 2),
       ]),
    _s(14, "O'qituvchi jamoaga qo'shimcha topshiriq berdi. Hamma band va hech kim uni olishni xohlamayapti.",
       'Преподаватель дал команде дополнительное задание. Все заняты, и никто не хочет его брать.', [
           ("Kimdir ixtiyoriy chiqishini kutasiz — majburan qilingan ish sifatli bo'lmaydi.",
            'Подождать, пока кто-то вызовется сам, — работа из-под палки не бывает качественной.', 1),
           ("Topshiriqni kichik qismlarga bo'lib, hammaga teng taqsimlashni taklif qilasiz.",
            'Предложить разбить задание на части и распределить поровну.', 4),
           ("O'zingiz olasiz va keyingi safar navbat boshqaga o'tishini kelishib olasiz.",
            'Взять его себе и договориться, что в следующий раз очередь за другим.', 3),
           ("O'qituvchiga jamoa bandligini aytib, muddatni uzaytirishni so'raysiz.",
            'Сказать преподавателю, что команда загружена, и попросить продлить срок.', 2),
       ]),
    _s(15, "Siz jamoadagi eng kuchli dasturchisiz. Bir a'zo sekin ishlaydi va sizga tez-tez savol beradi.",
       'Вы самый сильный программист в команде. Один участник работает медленно и часто задаёт вам вопросы.', [
           ("Savollariga javob berish o'rniga, kerakli qismni o'zingiz tezda yozib berasiz.",
            'Вместо ответов на вопросы быстро написать нужную часть за него.', 1),
           ("Kuniga bir marta qisqa vaqt ajratib, savollarini birga ko'rib chiqasiz.",
            'Раз в день выделять немного времени и разбирать его вопросы вместе.', 4),
           ("Unga foydali materiallar yuborib, avval o'zi urinib ko'rishini so'raysiz.",
            'Отправить полезные материалы и попросить сначала попробовать самому.', 3),
           ("Sardorga unga murakkab bo'lmagan vazifalar berishni taklif qilasiz.",
            'Предложить лидеру давать ему задачи попроще.', 2),
       ]),
    _s(16, "Jamoa loyihasiga umumiy baho qo'yiladi, lekin bir a'zo deyarli hech narsa qilmadi. O'qituvchi har kimning hissasi haqida so'radi.",
       'За командный проект ставится общая оценка, но один участник почти ничего не сделал. Преподаватель спрашивает о вкладе каждого.', [
           ("Hamma teng ishladi, deysiz — jamoadoshni sotib qo'ymaslik kerak.",
            'Сказать, что все работали одинаково, — своих не сдают.', 1),
           ("Har bir a'zo qilgan ishni faktlar asosida xolis aytib berasiz.",
            'Объективно, на фактах рассказать, что сделал каждый.', 4),
           ("Faqat o'z hissangiz haqida gapirasiz, boshqalarga baho bermaysiz.",
            'Рассказать только о своём вкладе, не оценивая других.', 2),
           ("Avval o'sha a'zo bilan gaplashib, o'qituvchiga nima deyishni birga kelishib olasiz.",
            'Сначала поговорить с этим участником и вместе решить, что сказать преподавателю.', 3),
       ]),
    _s(17, "A'zolar turli vaqtda ishlaydi va chatdagi muhim qarorlar boshqa xabarlar orasida yo'qolib ketyapti.",
       'Участники работают в разное время, и важные решения теряются среди сообщений в чате.', [
           ("Muhim qarorlarni alohida hujjatga yozishni taklif qilib, birinchisini o'zingiz yozasiz.",
            'Предложить фиксировать важные решения в отдельном документе и сделать первую запись самому.', 4),
           ("Har kuni ma'lum bir soatda hamma bir vaqtda onlayn bo'lishini talab qilasiz.",
            'Требовать, чтобы каждый день в определённый час все были онлайн одновременно.', 2),
           ("Qarorni o'tkazib yuborgan a'zo chat tarixini o'zi o'qishi kerak, deb hisoblaysiz.",
            'Считать, что пропустивший решение должен сам читать историю чата.', 1),
           ("Har hafta qisqa qo'ng'iroq o'tkazib, unda asosiy qarorlarni takrorlashni taklif qilasiz.",
            'Предложить раз в неделю проводить короткий созвон и проговаривать на нём все главные решения.', 3),
       ]),
    _s(18, "Jamoadoshingiz siz yozgan kod haqida keskin ohangda, lekin asosli izohlar qoldirdi.",
       'Коллега оставил к вашему коду резкие по тону, но обоснованные замечания.', [
           ("Izohlarning mazmuniga javob berasiz, ohang haqida esa keyin alohida gaplashasiz.",
            'Ответить по существу замечаний, а о тоне поговорить потом отдельно.', 4),
           ("Kelishmovchilik chiqmasligi uchun barcha izohlarni indamay tuzatib qo'yasiz.",
            'Чтобы не было конфликта, молча исправить всё по замечаниям.', 3),
           ("Avval izohlarni hurmat bilan yozishini so'raysiz, keyin tuzatasiz.",
            'Сначала попросить писать замечания уважительно, а потом исправить.', 2),
           ("Uning kodini ham xuddi shunday sinchkovlik bilan ko'rib chiqib, izohlar qoldirasiz.",
            'Так же придирчиво просмотреть его код и оставить замечания.', 1),
       ]),
    _s(19, "Siz vazifalarni taqsimladingiz, lekin bir a'zo o'ziga berilgan vazifa qiziq emasligini aytdi.",
       'Вы распределили задачи, но один участник говорит, что его задача ему неинтересна.', [
           ("Vazifalar hamma uchun adolatli bo'lishi kerakligini tushuntirib, taqsimotni o'zgartirmaysiz.",
            'Объяснить, что распределение должно быть справедливым для всех, и ничего не менять.', 2),
           ("Qaysi vazifa unga qiziqligini so'rab, jamoa bilan almashtirish mumkinligini ko'rib chiqasiz.",
            'Спросить, какая задача ему интересна, и обсудить с командой возможность обмена.', 4),
           ("Unga yoqadigan vazifani darhol berib, uning vazifasini o'zingiz olasiz.",
            'Сразу отдать ему интересную задачу, а его задачу взять себе.', 1),
           ("Hozircha shu vazifani bajarishini, keyingi taqsimotda xohishi hisobga olinishini aytasiz.",
            'Попросить пока выполнить эту задачу и пообещать учесть его пожелания при следующем распределении.', 3),
       ]),
    _s(20, "Jamoa loyihasi himoyasida bir a'zo komissiya savoliga javob bera olmay qoldi.",
       'На защите командного проекта один участник не может ответить на вопрос комиссии.', [
           ("Suhbatga qo'shilib, uning fikrini davom ettirishga yordam berasiz.",
            'Подключиться и помочь ему развить его мысль.', 4),
           ("Vaqt ketmasligi uchun savolga o'zingiz to'liq javob berasiz.",
            'Чтобы не терять время, полностью ответить на вопрос самому.', 2),
           ("Uning o'zi uddalashiga imkon berib, aralashmaysiz.",
            'Не вмешиваться, дать ему справиться самому.', 1),
           ("Himoyadan keyin unga qanday tayyorlanish kerakligini tushuntirasiz.",
            'После защиты объяснить ему, как нужно было подготовиться.', 3),
       ]),
    # -- Kelishuv va jarayon / координация и процесс --------------------------------
    _s(21, "Vazifalar ro'yxati chatda, jadvalda va og'zaki kelishuvlarda tarqoq — kim nima qilayotgani chalkash.",
       'Список задач разбросан по чату, таблице и устным договорённостям — непонятно, кто что делает.', [
           ("Har kuni ertalab kim nima qilayotganini umumiy chatda so'rab turasiz.",
            'Каждое утро спрашивать в общем чате, кто чем занят сегодня.', 2),
           ("Barcha vazifalarni bitta umumiy taxtaga ko'chirishni taklif qilasiz.",
            'Предложить перенести все задачи на одну общую доску.', 4),
           ("O'z vazifalaringizni bilganingiz uchun chalkashlikka aralashmaysiz.",
            'Раз свои задачи вы знаете, в эту путаницу не вмешиваться.', 1),
           ("Sardordan vazifalarni bitta joyda yuritish tartibini o'rnatishni so'raysiz.",
            'Попросить лидера установить порядок ведения задач в одном месте.', 3),
       ]),
    _s(22, "Jamoa yig'ilishlari bir soat davom etadi, lekin vaqtning ko'p qismi mavzudan chetga ketadi.",
       'Встречи команды длятся час, но большая часть времени уходит на посторонние темы.', [
           ("Yig'ilish oldidan qisqa kun tartibi tuzishni taklif qilasiz.",
            'Предложить заранее составлять короткую повестку.', 4),
           ("Mavzudan chetga chiqilganda suhbatni asosiy savolga qaytarasiz.",
            'Когда разговор уходит в сторону, возвращать его к главному вопросу.', 3),
           ("Yig'ilish vaqtini yarim soatga qisqartirishni taklif qilasiz.",
            'Предложить сократить время встречи вдвое, до получаса.', 2),
           ("Yig'ilishning ikkinchi yarmida o'z ishingiz bilan shug'ullanasiz.",
            'Во второй половине встречи заниматься своей работой.', 1),
       ]),
    _s(23, "Ikki a'zo bir hafta davomida bir xil funksiyani bir-biridan bexabar ikki marta yozibdi.",
       'Двое участников за неделю дважды написали одну и ту же функцию, не зная друг о друге.', [
           ("Ish boshlashdan oldin kim nimani olayotganini yozib qo'yish qoidasini taklif qilasiz.",
            'Предложить правило: перед началом работы фиксировать, кто что берёт.', 4),
           ("Takrorlanish haqida hech kimga aytmay, ikkinchi variantni jimgina o'chirib tashlab qo'yasiz.",
            'Никому не говоря о дублировании, тихо удалить второй вариант из проекта.', 1),
           ("Ikkala variantni bir-biri bilan solishtirib, yaxshirog'ini qoldirishni taklif qilasiz.",
            'Предложить сравнить оба варианта между собой и оставить тот, что лучше.', 3),
           ("Keyingi safar bunday bo'lmasligi uchun diqqatliroq bo'lishni chatda eslatasiz.",
            'Напомнить в чате, что в следующий раз нужно быть внимательнее.', 2),
       ]),
    _s(24, "Jamoa a'zolari turli shaharlarda; umumiy qo'ng'iroqqa har safar kimdir kelolmaydi.",
       'Участники команды в разных городах: на общий созвон каждый раз кто-то не попадает.', [
           ("Qo'ng'iroqni yozib olib, kelolmaganlarga keyin yuborishni taklif qilasiz.",
            'Предложить записывать созвон и потом отправлять тем, кто не смог.', 3),
           ("Qaror talab qiladigan masalalarni hamma bo'sh bo'lgan bitta vaqtga to'playsiz.",
            'Собирать вопросы, требующие решения, на одно время, когда свободны все.', 4),
           ("Kelolmaganlar keyin o'zlari xabardor bo'lib olishi kerak, deb hisoblaysiz.",
            'Считать, что пропустившие созвон должны сами узнавать обо всём.', 1),
           ("Qaror qabul qilishni har safar o'sha kuni kelganlar zimmasiga qoldirasiz.",
            'Каждый раз оставлять принятие решений тем, кто в этот день пришёл.', 2),
       ]),
    _s(25, "Loyihada hech kim hujjat yozmaydi; yangi kelgan har bir odam hammadan qaytadan so'raydi.",
       'В проекте никто не пишет документацию: каждый новый человек переспрашивает всех заново.', [
           ("Eng ko'p so'raladigan savollarni bitta faylga yozib borishni boshlaysiz.",
            'Начать записывать самые частые вопросы в один файл.', 4),
           ("Barcha savollarga javob berishni butunlay o'zingiz zimmangizga olasiz.",
            'Взять ответы на все вопросы новых людей полностью на себя.', 2),
           ("Har bir a'zodan o'z qismi bo'yicha besh qator izoh yozishni so'raysiz.",
            'Попросить каждого написать по пять строк пояснений о своей части.', 3),
           ("Hozir vaqt yo'qligini aytib, hujjatni loyiha tugagandan keyinga qoldirasiz.",
            'Сказать, что сейчас некогда, и отложить документацию на после проекта.', 1),
       ]),
    _s(26, "Jamoada muddatlar og'zaki kelishiladi va tez-tez «ertaga» deb suriladi.",
       'В команде сроки договариваются устно и часто сдвигаются «на завтра».', [
           ("Kechikayotgan a'zolarni har kuni shaxsan eslatib, turtkilab turasiz.",
            'Каждый день лично напоминать тем, кто опаздывает, и подталкивать их.', 2),
           ("Haftaning o'rtasida qisqa nazorat nuqtasini kiritishni taklif qilasiz.",
            'Предложить ввести короткую контрольную точку в середине недели.', 3),
           ("Muddatlar baribir suriladi deb, o'z ishingizni oldindan tugatib qo'yasiz.",
            'Раз сроки всё равно сдвигаются, просто заканчивать своё заранее.', 1),
           ("Har bir vazifaga aniq sana qo'yib, uni umumiy jadvalga yozasiz.",
            'Ставить каждой задаче конкретную дату и записывать в общий график.', 4),
       ]),
    _s(27, "Jamoa chatida savollar javobsiz qoladi: har kim «boshqa birov javob beradi» deb o'ylaydi.",
       'В чате команды вопросы остаются без ответа: каждый думает, что ответит кто-то другой.', [
           ("Har bir savolga kim javob berishini darhol belgilashni taklif qilasiz.",
            'Предложить сразу назначать, кто отвечает на каждый вопрос.', 4),
           ("Javobsiz qolgan savollarni kun oxirida bitta ro'yxatga yig'ib chiqasiz.",
            'В конце дня собирать оставшиеся без ответа вопросы в один список.', 3),
           ("Savol berganlarga to'g'ridan-to'g'ri shaxsiy yozishni maslahat berasiz.",
            'Советовать задающим писать напрямую в личные сообщения.', 2),
           ("Boshqalarni kutmay, barcha savollarga o'zingiz javob berib turasiz.",
            'Не дожидаясь других, самому отвечать на все вопросы в чате подряд.', 1),
       ]),
    _s(28, "Jamoa ishni bo'lib oldi, lekin qismlar bir-biriga ulanmayapti — ulanish nuqtalari kelishilmagan.",
       'Команда разделила работу, но части не стыкуются — точки соединения не согласованы.', [
           ('Har bir qismga alohida moslashtiruvchi qatlam yozib chiqasiz.',
            'Написать отдельный слой-адаптер под каждую часть.', 2),
           ("Boshqalar o'z qismini sizning qismingizga moslashtirishini so'raysiz.",
            'Попросить остальных подогнать свои части под вашу.', 1),
           ("Kod yozishdan oldin ulanish nuqtalarini birga kelishib olasiz.",
            'До написания кода вместе согласовать точки стыковки.', 4),
           ("Ulanish muammolarini ko'rib chiqish uchun alohida uchrashuv tayinlaysiz.",
            'Назначить отдельную встречу, чтобы разобрать проблемы стыковки.', 3),
       ]),
    _s(29, "Jamoa har bir mayda qaror uchun ham hammani chaqiradi, shu sababli ish sekinlashgan.",
       'Команда собирает всех даже ради мелких решений, из-за этого работа замедлилась.', [
           ("Mayda qarorlarni vazifa egasining o'zi hal qilsin, deb taklif qilasiz.",
            'Предложить, чтобы мелкие решения принимал сам владелец этой задачи.', 3),
           ("Yig'ilishlar sonini kamaytirish kerakligini jamoa oldida ko'tarasiz.",
            'Поднять перед командой вопрос о том, чтобы сократить число встреч.', 2),
           ("Qaysi qarorlar birgalikda, qaysilari mustaqil qabul qilinishini kelishasiz.",
            'Договориться, какие решения принимаются вместе, а какие — самостоятельно.', 4),
           ("Vaqtni tejash uchun mayda qarorlar muhokamasiga qo'shilmay qo'yasiz.",
            'Чтобы экономить время, перестать участвовать в обсуждении мелочей.', 1),
       ]),
    _s(30, "Jamoa yangi ish taxtasiga o'tdi, lekin a'zolarning yarmi hali eskisidan foydalanmoqda.",
       'Команда перешла на новую доску задач, но половина участников ещё пользуется старой.', [
           ("Eski taxtada qolgan a'zolarga yangisini ko'rsatib berasiz.",
            'Показать новую доску тем участникам, кто остался на старой.', 3),
           ("O'tish sanasini belgilab, keyin eskisini yopishni kelishasiz.",
            'Назначить дату перехода и после неё закрыть старую доску.', 4),
           ("Ikkala taxtani kuzatib, ma'lumotni qo'lda ko'chirib turasiz.",
            'Следить за обеими досками и переносить данные вручную.', 2),
           ("Har kim o'ziga qulay taxtadan foydalanaversin, deb qo'ya qolasiz.",
            'Сказать: пусть каждый пользуется удобной ему доской.', 1),
       ]),
    # -- Nizo va kelishmovchilik / конфликты и разногласия ---------------------------
    _s(31, "Ikki a'zo texnik masalada bir necha kundan beri kelisha olmayapti, bahs shaxsiyatga o'tyapti.",
       'Двое участников несколько дней не могут договориться по техническому вопросу, спор переходит на личности.', [
           ("Ikkalasiga ham qo'shilmay jim turasiz — o'zlari kelishib olishadi.",
            'Не поддерживать никого и промолчать — сами договорятся.', 1),
           ("Bahsni to'xtatib, qaror mezonlarini aniqlashni taklif qilasiz.",
            'Остановить спор и предложить определить критерии решения.', 4),
           ("Ikkalasidan o'z variantini kichik namunada sinab ko'rishni so'raysiz.",
            'Попросить обоих проверить свой вариант на небольшом примере.', 3),
           ('Bahsni ertaga qoldirib, hozircha hammani tinchlanishga chaqirasiz.',
            'Отложить спор на завтра и пока призвать всех успокоиться.', 2),
       ]),
    _s(32, "Jamoadoshingiz sizning taklifingizni yig'ilishda keskin rad etdi, sababini aytmadi.",
       'Коллега резко отверг ваше предложение на встрече, не назвав причину.', [
           ("Taklifingizni batafsil yozma ko'rinishda tayyorlab, qayta taqdim etasiz.",
            'Подготовить предложение подробно в письменном виде и представить снова.', 3),
           ("Boshqa a'zolardan fikr so'rab, qo'llab-quvvatlash to'playsiz.",
            'Спросить мнение других участников и собрать поддержку.', 2),
           ("Undan taklif qaysi jihati bilan ishlamasligini so'raysiz.",
            'Спросить у него, чем именно предложение не сработает.', 4),
           ("Bundan keyin uning oldida umuman taklif kiritmay qo'yasiz.",
            'Впредь вообще не вносить никаких предложений при нём.', 1),
       ]),
    _s(33, "Jamoa ikkiga bo'lindi: yarmi tezroq topshirishni, yarmi sifatni oshirishni xohlaydi.",
       'Команда раскололась: половина хочет сдать быстрее, половина — повысить качество.', [
           ("Minimal talablarni birga yozib, qolganini vaqt qolsa qilishni kelishasiz.",
            'Вместе записать минимальные требования, остальное — если останется время.', 4),
           ("O'z tarafingizni qat'iy himoya qilib, boshqalarni ham ko'ndirishga urinasiz.",
            'Твёрдо отстаивать свою сторону и пытаться переубедить всех остальных участников.', 1),
           ("Ikkala tarafdan ham o'z talabining nimasidan voz kecha olishini so'raysiz.",
            'Спросить у обеих сторон, какой частью каждая готова пожертвовать.', 3),
           ("Ovoz berib, ko'pchilik qaysi tarafda bo'lsa, o'shani tanlaysiz.",
            'Проголосовать и выбрать ту сторону, за которую большинство.', 2),
       ]),
    _s(34, "Jamoadoshingiz siz bilan kelishmasdan, o'z bilganicha loyiha tuzilmasini o'zgartirib qo'ygan.",
       'Коллега, не согласовав с вами, по своему усмотрению изменил структуру проекта.', [
           ("O'zgarishni darhol orqaga qaytarib qo'yib, keyin unga xabar berasiz.",
            'Сразу откатить изменение назад, а потом сообщить ему об этом.', 2),
           ("Bunday o'zgarishlar jamoada qabul qilinmasligini chatda hammaga yozasiz.",
            'Написать всем в общий чат, что такие изменения в команде недопустимы.', 1),
           ("O'zgarish sabablarini so'rab, keyin jamoa bilan ochiq muhokama qilasiz.",
            'Спросить о причинах изменения, а потом открыто обсудить с командой.', 4),
           ("O'zgarishni vaqtincha qoldirib, qaysi biri yaxshiroq ekanini o'lchaysiz.",
            'Пока оставить изменение и измерить, какой из вариантов лучше.', 3),
       ]),
    _s(35, "Yig'ilishda ikki a'zo uchinchisining gapini masxara qilib kulishdi, u esa jim qoldi.",
       'На встрече двое подняли на смех слова третьего, и тот замолчал.', [
           ('Hazil deb qabul qilib, jamoaning kayfiyatini buzmaslik uchun indamaysiz.',
            'Воспринять как шутку и промолчать, чтобы не портить настрой.', 1),
           ("Yig'ilishdan keyin masxara qilganlar bilan alohida gaplashasiz.",
            'После встречи поговорить с насмешниками отдельно.', 3),
           ("Suhbatni to'xtatib, bunday ohang ishga xalaqit berayotganini aytasiz.",
            'Остановить разговор и сказать, что такой тон мешает работе.', 4),
           ("Jim qolgan a'zodan fikrini so'rab, suhbatni ish mavzusiga qaytarasiz.",
            'Спросить мнение замолчавшего и вернуть разговор к рабочей теме.', 2),
       ]),
    _s(36, "Kodingizni tekshirishi kerak bo'lgan jamoadosh bir necha kundan beri javob bermayapti, ish to'xtab qoldi.",
       'Коллега, который должен проверить ваш код, несколько дней не отвечает, и работа стоит.', [
           ('Unga aniq muddat taklif qilib, ulgurmasa boshqasiga murojaat qilasiz.',
            'Предложить ему срок и сказать, что иначе попросите другого.', 4),
           ("Ko'proq kutib o'tirmay, tekshiruvsiz kodni o'zingiz birlashtirib yuborasiz.",
            'Больше не ждать и влить свой код в проект без всякой проверки.', 1),
           ("Tekshiruvni boshqa a'zodan so'rashni sardor bilan kelishasiz.",
            'Согласовать с лидером, что проверку сделает другой участник.', 3),
           ('Javob kelmaguncha har kuni unga eslatma yuborib, kutib turasiz.',
            'Каждый день отправлять ему напоминание и ждать ответа.', 2),
       ]),
    _s(37, "Sizning vazifangiz boshqa a'zoning ishiga bog'liq, u esa har kuni «hali tayyor emas» deyaveradi.",
       'Ваша задача зависит от работы другого участника, а он каждый день говорит «ещё не готово».', [
           ('U tayyorlagunicha vaqtingizni boshqa vazifalarga sarflaysiz.',
            'Пока он не готов, тратить время на другие свои задачи.', 2),
           ("Undan qaysi qismi tayyor ekanini so'rab, o'sha qismdan boshlaysiz.",
            'Спросить, какая часть уже готова, и начать с неё.', 4),
           ("Uning qismini o'zingiz yozib, keyin jimgina almashtirib qo'yasiz.",
            'Написать его часть самому, а потом тихо подменить.', 1),
           ("Bog'liqlikni sardorga aytib, muddatlarni qayta ko'rishni so'raysiz.",
            'Сообщить о зависимости лидеру и попросить пересмотреть сроки.', 3),
       ]),
    _s(38, "Jamoada bitta a'zoning fikri doim inobatga olinadi, boshqalarniki e'tiborsiz qoladi.",
       'В команде мнение одного участника всегда учитывают, а остальных оставляют без внимания.', [
           ("Har bir taklifni bir xil savollar bilan baholash tartibini kiritasiz.",
            'Ввести порядок, при котором предложения оценивают одинаково.', 4),
           ("Uning fikri odatda to'g'ri chiqadi, shuning uchun aralashmaysiz.",
            'Раз его мнение обычно верное, ни во что не вмешиваться.', 1),
           ("E'tibordan chetda qolgan takliflarni yig'ilishda qayta ko'tarasiz.",
            'Снова поднять на встрече предложения, оставшиеся без внимания.', 3),
           ("O'sha a'zoga yig'ilishda boshqalarga ham imkon berishini aytasiz.",
            'Сказать этому участнику, чтобы на встречах давал слово и другим.', 2),
       ]),
    _s(39, "Jamoadoshingiz ochiqdan-ochiq «bu loyiha baribir yaxshi baho olmaydi» deb aytdi.",
       'Коллега открыто заявил: «этот проект всё равно не получит хорошую оценку».', [
           ("Bunday gaplarga e'tibor bermay, ishni davom ettirasiz.",
            'Не обращать внимания на такие слова и продолжать работу.', 1),
           ("Loyihaning kuchli tomonlarini ko'rsatib, uni ishontirishga urinasiz.",
            'Показать сильные стороны проекта и попробовать его убедить.', 3),
           ("Bunday gaplar jamoani tushiradi, deb undan iltimos qilasiz.",
            'Попросить его так не говорить — это демотивирует команду.', 2),
           ("Uning shubhasi nimadan kelib chiqqanini so'raysiz.",
            'Спросить, из-за чего у него такие сомнения.', 4),
       ]),
    _s(40, "Muhokamada sizning xatoyingiz aniqlandi va jamoadoshingiz buni hammaning oldida aytdi.",
       'На обсуждении нашли вашу ошибку, и коллега сказал об этом при всех.', [
           ('Xato qanday yuzaga kelganini batafsil tushuntirib berasiz.',
            'Подробно объяснить, как эта ошибка возникла.', 2),
           ("Xatoni tan olasiz, ohang haqida esa keyin alohida gaplashasiz.",
            'Признать ошибку, а о тоне поговорить потом наедине.', 3),
           ("Xatoni tan olib, uni qanday tuzatishni darhol aytasiz.",
            'Признать ошибку и сразу сказать, как её исправить.', 4),
           ("Xato unchalik muhim emasligini aytib, mavzuni yopasiz.",
            'Сказать, что ошибка несущественная, и закрыть тему.', 1),
       ]),
    # -- Javobgarlik va ochiqlik / ответственность и прозрачность --------------------
    _s(41, "Va'da qilgan qismingizni bugun tugata olmasligingiz aniq bo'ldi, muddat esa ertaga.",
       'Стало ясно, что обещанную часть сегодня вы не закончите, а срок — завтра.', [
           ("Tayyor bo'lgan qismini topshirib, qolgani haqida umuman gapirmaysiz.",
            'Сдать готовую часть и вообще ничего не говорить об остальном.', 1),
           ("Hozir jamoaga aytib, qolgan qismni kim qilishini birga hal qilasiz.",
            'Сразу сказать команде и вместе решить, кто доделает остаток.', 4),
           ('Kechasi ishlab, ertalabgacha ulgurishga urinasiz, keyin aytasiz.',
            'Поработать ночью, попробовать успеть к утру, а потом сказать.', 2),
           ("Nima tayyor, nima yo'qligini yozib, sardorga yuborib qo'yasiz.",
            'Написать, что готово, а что нет, и отправить это лидеру.', 3),
       ]),
    _s(42, "Jamoa sizning qismingizni tayyor deb hisoblayapti, aslida esa u faqat oddiy holatlarda ishlaydi.",
       'Команда считает вашу часть готовой, а на деле она работает только в простых случаях.', [
           ("Aynan qaysi holatlarda ishlamasligini aytib, muddat so'raysiz.",
            'Сказать, в каких именно случаях она не работает, и попросить срок.', 4),
           ("Ishlamaydigan holatlar kam uchraydi deb, ularga e'tibor bermaysiz.",
            'Решить, что такие случаи редки, и вообще не обращать на них внимания.', 1),
           ("Ishlamaydigan qismni belgilab, chatga qisqacha yozib qo'yasiz.",
            'Отметить нерабочую часть и коротко написать об этом в общий чат.', 3),
           ("Xatoni tuzatib bo'lgunga qadar bu haqda hech kimga aytmaysiz.",
            'Ничего никому не говорить, пока не исправите эту ошибку.', 2),
       ]),
    _s(43, "Ish boshlagach, sizga berilgan vazifa bilimingizdan ancha yuqori ekanini tushundingiz.",
       'Начав работу, вы поняли, что доставшаяся задача заметно выше вашего уровня.', [
           ('Bilmasligingiz bilinib qolmasligi uchun indamay ishni davom ettirasiz.',
            'Чтобы не выдать своё незнание, молча продолжать работу дальше.', 1),
           ("Buni darhol aytib, yordam yoki vazifani almashtirishni so'raysiz.",
            'Сразу сказать об этом и попросить помощи или замены задачи.', 4),
           ("Vazifani bilimingiz yetadigan darajada soddalashtirib bajarasiz.",
            'Упростить задачу до своего уровня и сделать в таком виде.', 2),
           ("Bir kun mustaqil o'rganib ko'rib, keyin holatni jamoaga aytasiz.",
            'День поразбираться самому, а потом рассказать команде о ситуации.', 3),
       ]),
    _s(44, "Jamoa umumiy xatoga yo'l qo'ydi, o'qituvchi esa sababini so'rayapti.",
       'Команда допустила общую ошибку, и преподаватель спрашивает о причине.', [
           ("Qaror qanday qabul qilinganini xolis tushuntirib berasiz.",
            'Объективно объяснить, как принималось это решение.', 4),
           ("Kim taklif qilgan bo'lsa, o'shaning ismini o'qituvchiga aytasiz.",
            'Назвать преподавателю имя того, кто именно это предложил.', 1),
           ("Xatoni jamoa nomidan tan olib, tuzatish rejasini aytasiz.",
            'Признать ошибку от имени команды и рассказать план исправления.', 3),
           ('Qaror sizning ishtirokingizsiz qabul qilinganini aytasiz.',
            'Сказать, что решение принимали без вашего участия.', 2),
       ]),
    _s(45, "Jamoadoshingiz o'z xatosini boshqa a'zoga to'nkamoqda.",
       'Коллега перекладывает свою ошибку на другого участника.', [
           ("Faktlarni ko'rsatib, kim nima qilgani aniq bo'lishiga erishasiz.",
            'Показать факты, чтобы стало ясно, кто что сделал.', 4),
           ("Aybi yo'q a'zoni ochiq qo'llab-quvvatlab, mavzuni yopasiz.",
            'Поддержать невиновного участника и закрыть тему.', 2),
           ("U bilan alohida gaplashib, xatoni tan olishini so'raysiz.",
            'Поговорить с ним наедине и попросить признать ошибку.', 3),
           ("Bahsga qo'shilmasdan, ish o'z yo'lida davom etaversin deysiz.",
            'Не вмешиваться в спор — пусть работа идёт дальше.', 1),
       ]),
    _s(46, "Jamoa siz qarshi bo'lgan yo'lni tanladi, endi shu yo'lda ishlash kerak.",
       'Команда выбрала путь, против которого вы были, и теперь работать нужно по нему.', [
           ("Xato ekani ko'rinib qolganda «men aytgandim» deyish uchun kutib turasiz.",
            'Ждать подходящего момента, чтобы потом сказать всем «я же говорил».', 1),
           ("Qarorni to'liq bajarasiz, xavfli joylarni oldindan belgilab qo'yasiz.",
            'Полностью выполнять решение, заранее отметив рискованные места.', 4),
           ("Bajarasiz, lekin fikringiz o'zgarmaganini bir marta aytib qo'yasiz.",
            'Выполнять, но один раз сказать, что ваше мнение не изменилось.', 3),
           ("Vazifani minimal darajada bajarib, natijaga javobgar bo'lmaysiz.",
            'Сделать всё по минимуму и не брать ответственность за результат.', 2),
       ]),
    _s(47, "Jamoadoshingiz qismini tekshirib berishni so'radi, lekin sizda ham muddat yaqin.",
       'Коллега попросил проверить его часть, но у вас самих близкий срок.', [
           ("Qachon tekshira olishingizni aniq aytib, o'sha vaqtda tekshirasiz.",
            'Сказать точно, когда сможете проверить, и проверить в это время.', 4),
           ('Roziligingizni bildirasiz, lekin ulgurmasangiz oldindan ogohlantirmaysiz.',
            'Согласиться, но если вдруг не успеете — заранее не предупреждать.', 1),
           ("Eng muhim joyini hozir, qolganini keyinroq ko'rishni taklif qilasiz.",
            'Предложить посмотреть сейчас самое важное, остальное — позже.', 3),
           ("Band ekaningizni aytib, boshqadan so'rashini maslahat berasiz.",
            'Сказать, что вы заняты, и посоветовать попросить другого.', 2),
       ]),
    _s(48, "Sizning qismingiz tayyor, jamoaning qolgan qismi orqada. Muddatgacha ikki kun bor.",
       'Ваша часть готова, остальная команда отстаёт. До срока два дня.', [
           ("Bo'sh vaqtingizda umumiy tekshiruv va tayyorgarlikni qilasiz.",
            'В свободное время заняться общей проверкой и подготовкой.', 3),
           ("Qolgan vaqtda o'z qismingizni yaxshilash bilan shug'ullanasiz.",
            'В оставшееся время заниматься улучшением своей части.', 2),
           ("Kimga yordam kerakligini so'rab, orqada qolgan joyga qo'shilasiz.",
            'Спросить, кому нужна помощь, и подключиться к отстающему.', 4),
           ("O'z ishingiz tugagani uchun jamoaning qolganini kutib o'tiraverasiz.",
            'Раз ваша работа закончена, спокойно ждать остальных.', 1),
       ]),
    _s(49, "Jamoadoshingiz «bu vazifani men olaman» dedi, lekin uch kundan beri natija ko'rinmayapti.",
       'Коллега сказал «эту задачу беру я», но уже три дня результата не видно.', [
           ("Yig'ilishgacha kutib turasiz, o'sha yerda ma'lum bo'ladi.",
            'Подождать до встречи — там всё выяснится.', 2),
           ("Vazifani undan butunlay olib, boshqa a'zoga berasiz.",
            'Забрать у него задачу совсем и отдать другому.', 1),
           ("Vazifani kichikroq bosqichlarga bo'lishni taklif qilasiz.",
            'Предложить разбить задачу на более мелкие шаги.', 3),
           ("Undan bugun nimani ko'rsata olishini so'raysiz.",
            'Спросить, что он может показать уже сегодня.', 4),
       ]),
    _s(50, "Jamoa loyihani topshirdi, keyin esa sizning qismingizda xato borligi ma'lum bo'ldi.",
       'Команда сдала проект, а потом выяснилось, что в вашей части есть ошибка.', [
           ('Topshirilgan ish baribir qaytarilmaydi deb hisoblab, jim qolaverasiz.',
            'Раз работа уже сдана и её всё равно не вернут, просто промолчать.', 1),
           ("Xatoni jamoaga aytib, o'qituvchiga qanday xabar berishni kelishasiz.",
            'Сказать команде об ошибке и решить, как сообщить преподавателю.', 4),
           ("Baho qo'yilgunicha kutib turib, undan keyin qarorga kelasiz.",
            'Подождать до выставления оценки и только потом решать.', 2),
           ("Tuzatilgan variantni o'zingiz tayyorlab, jamoaga taqdim etasiz.",
            'Самому подготовить исправленный вариант и показать команде.', 3),
       ]),
    # -- Muloqot va qayta aloqa / коммуникация и обратная связь ----------------------
    _s(51, "Jamoadoshingiz yozgan kod ishlaydi, lekin uni o'qib tushunish juda qiyin.",
       'Код, написанный коллегой, работает, но читать и понимать его очень трудно.', [
           ("Aniq joylarni ko'rsatib, nimani soddalashtirish mumkinligini yozasiz.",
            'Указать конкретные места и написать, что можно упростить.', 4),
           ("Kodni o'zingiz qayta yozib chiqib, unga tayyor holda ko'rsatasiz.",
            'Переписать код самому и показать ему уже готовый вариант.', 2),
           ("Umumiy uslub qoidalarini jamoa bilan kelishib olishni taklif qilasiz.",
            'Предложить команде договориться об общих правилах стиля.', 3),
           ("Kod ishlayotganini hisobga olib, hech qanday izoh yozmay qo'yaverasiz.",
            'Раз код работает, вообще не писать никаких замечаний к нему.', 1),
       ]),
    _s(52, "Siz uzoq ishlagan taklifni jamoa besh daqiqada rad etdi.",
       'Предложение, над которым вы долго работали, команда отвергла за пять минут.', [
           ("Rad etish sabablarini aniq so'rab, ularni yozib olasiz.",
            'Спросить конкретные причины отказа и записать их.', 4),
           ("Xafa bo'lganingizni bildirmasdan, bu mavzuni yopasiz.",
            'Не показывать обиду и закрыть эту тему совсем.', 1),
           ("Qaror shoshilinch qabul qilindi deb, qayta muhokamani so'raysiz.",
            'Сказать, что решение приняли поспешно, и попросить обсудить снова.', 2),
           ("Taklifni sabablarni hisobga olib qayta ishlab chiqasiz.",
            'Переработать предложение с учётом этих причин.', 3),
       ]),
    _s(53, "Jamoaga muhim yangilikni yetkazish kerak, lekin u ba'zi a'zolarga yoqmaydi.",
       'Нужно донести до команды важную новость, но некоторым участникам она не понравится.', [
           ("Yangilikni sababi bilan birga hammaga bir vaqtda aytasiz.",
            'Сообщить новость всем одновременно и вместе с причиной.', 4),
           ("Avval eng ko'p ta'sirlanadigan a'zolar bilan gaplashasiz.",
            'Сначала поговорить с теми, кого это коснётся сильнее всего.', 3),
           ("Yangilikni bitta qisqa xabar qilib chatga yozib qo'yasiz.",
            'Написать новость одним коротким сообщением в общий чат.', 2),
           ("Vaziyat o'z-o'zidan ma'lum bo'lib qolishini kutib turasiz.",
            'Подождать, пока ситуация сама станет всем понятной без вас.', 1),
       ]),
    _s(54, "Jamoadoshingiz sizning izohlaringizni tanqid deb qabul qilib, har safar xafa bo'ladi.",
       'Коллега воспринимает ваши замечания как критику и каждый раз обижается.', [
           ("Izohlarni kamaytirib, faqat eng muhimlarini aytasiz.",
            'Сократить замечания и говорить только самые важные.', 2),
           ("Izohlarni shaxsga emas, kod va natijaga qaratasiz.",
            'Адресовать замечания коду и результату, а не человеку.', 4),
           ("Izoh yozishni to'xtatib, kerakli joyni tuzatasiz.",
            'Перестать писать замечания и править нужное самому.', 1),
           ("Izohlardan oldin nima yaxshi chiqqanini ham aytasiz.",
            'Перед замечаниями говорить и о том, что получилось хорошо.', 3),
       ]),
    _s(55, "Yig'ilishda hamma rozi bo'ldi, keyin esa har kim boshqa narsani tushunganini bildingiz.",
       'На встрече все согласились, а потом выяснилось, что каждый понял по-своему.', [
           ("Kelishuvni bir necha qator qilib yozib, tasdiqlashni so'raysiz.",
            'Записать договорённость и попросить всех подтвердить.', 4),
           ("Har kimdan o'zi nimani tushunganini yozib berishni so'raysiz.",
            'Попросить каждого написать, как именно он это понял.', 2),
           ("Yig'ilish oxirida xulosani ovoz chiqarib takrorlashni odat qilasiz.",
            'Завести привычку в конце встречи проговаривать итог вслух.', 3),
           ("Ishlash jarayonida hammasi o'z-o'zidan oydinlashadi deb hisoblaysiz.",
            'Считать, что по ходу работы всё прояснится само собой.', 1),
       ]),
    _s(56, "Jamoadoshingiz har safar «hammasi yaxshi» deb javob beradi, lekin ishi orqada qolmoqda.",
       'Коллега каждый раз отвечает «всё хорошо», но его работа отстаёт.', [
           ("Aytganiga ishonib, bundan keyin boshqa hech narsa so'ramaysiz.",
            'Поверить ему на слово и больше вообще ни о чём не спрашивать.', 1),
           ("Umumiy savol o'rniga aniq savol berasiz: qaysi qism tayyor?",
            'Вместо общего вопроса задать конкретный: какая часть готова?', 4),
           ("Ishini kuzatib turib, xulosani keyin o'zingiz chiqarasiz.",
            'Наблюдать за его работой и делать выводы самостоятельно.', 2),
           ("Ishini birga ko'rib chiqish uchun qisqa vaqt so'raysiz.",
            'Попросить немного времени, чтобы вместе посмотреть работу.', 3),
       ]),
    _s(57, "Jamoa sizning xabarlaringizga sovuq javob berayotganini sezdingiz.",
       'Вы заметили, что команда холодно отвечает на ваши сообщения.', [
           ("Bevosita so'raysiz: xabarlarimda nimadir noto'g'rimi?",
            'Спросить прямо: что-то не так в том, как я пишу?', 4),
           ("Bu sizga tuyulgandir deb, unga umuman e'tibor bermaysiz.",
            'Решить, что вам показалось, и не обращать внимания.', 1),
           ("Xabarlaringiz ohangini qayta o'qib, qisqartirasiz.",
            'Перечитать тон своих сообщений и сделать их короче.', 3),
           ("Muhim narsalarni chat o'rniga qo'ng'iroqda aytasiz.",
            'Важное говорить на созвоне, а не писать в общем чате.', 2),
       ]),
    _s(58, "Jamoada bir a'zo faqat o'z tilida yozadi, boshqalar esa uni to'liq tushunmaydi.",
       'Один участник пишет только на своём языке, и остальные понимают его не полностью.', [
           ("Tushunmagan odam o'zi so'rab, aniqlab olishi kerak deb hisoblaysiz.",
            'Считать, что непонявший должен сам спросить и уточнить.', 1),
           ("Jamoa bilan muhim xabarlar qaysi tilda yozilishini kelishasiz.",
            'Договориться с командой о языке важных сообщений.', 4),
           ("O'sha a'zodan xabarlarni qisqaroq va soddaroq yozishni so'raysiz.",
            'Попросить этого участника писать сообщения короче и проще.', 2),
           ("Tushunilmagan xabarlarni tarjima qilib, chatga qo'shasiz.",
            'Переводить непонятые сообщения и добавлять перевод в чат.', 3),
       ]),
    _s(59, "Jamoadosh sizga uzun ovozli xabarlar yuboradi, siz esa ularni eshitishga ulgurmaysiz.",
       'Коллега шлёт вам длинные голосовые, а вы не успеваете их слушать.', [
           ('Xabarni eshitmay turib ham, «tushundim» deb javob berasiz.',
            'Не прослушав сообщение, всё равно отвечать «понял».', 1),
           ("Ovozli xabarlarni kuniga bir marta ko'rib chiqishni kelishasiz.",
            'Договориться разбирать голосовые раз в день.', 3),
           ("Unga aytasiz: vazifaga oid narsalarni qisqa matn qilib yozsin.",
            'Сказать ему писать по задаче коротким текстом.', 4),
           ("Javob bermay qo'yasiz — chindan muhim bo'lsa, qayta yozadi.",
            'Перестать отвечать — если важно, напишет снова.', 2),
       ]),
    _s(60, "O'qituvchi jamoadan haftalik hisobot so'radi, uni kim yozishi noaniq.",
       'Преподаватель попросил у команды еженедельный отчёт, но неясно, кто его пишет.', [
           ("Hisobotni doim yozadigan bitta a'zoni tayinlashni so'raysiz.",
            'Попросить назначить одного постоянного ответственного за отчёт.', 2),
           ('Navbat tartibini taklif qilib, birinchi haftani olasiz.',
            'Предложить очерёдность и взять первую неделю на себя.', 4),
           ("Kimdir baribir yozib qo'yar deb, hisobot haqida gapirmaysiz.",
            'Не поднимать тему отчёта: кто-нибудь всё равно напишет.', 1),
           ("Har kim o'z qismi haqida ikki qator yozsin, deb taklif qilasiz.",
            'Предложить, чтобы каждый написал две строки о своей части.', 3),
       ]),
    # -- Yordam va o'rgatish / помощь и наставничество -------------------------------
    _s(61, "Jamoadoshingiz bir necha marta tushuntirilgan savolni yana so'rayapti.",
       'Коллега снова задаёт вопрос, который вы объясняли уже несколько раз.', [
           ('Bir xil savollardan charchaganingizni unga ochiqdan-ochiq bildirasiz.',
            'Открыто дать понять, что вы устали от одних и тех же вопросов.', 1),
           ("Javobni yozib qo'yib, keyingi safar shu yozuvga yo'naltirasiz.",
            'Записать ответ и в следующий раз отправлять к этой записи.', 4),
           ("Avval o'zi urinib ko'rishini, keyin savol berishini so'raysiz.",
            'Попросить сначала попробовать самому, а потом спрашивать.', 2),
           ('Savolni yana bir bor, butunlay boshqacha qilib tushuntirasiz.',
            'Объяснить ещё раз, но совсем по-другому, другими словами.', 3),
       ]),
    _s(62, "Yangi a'zo birinchi vazifasini noto'g'ri bajardi va buni o'zi sezmayapti.",
       'Новый участник сделал первую задачу неправильно и сам этого не замечает.', [
           ("Natijani birga ko'rib chiqib, qayerda chalkashganini ko'rsatasiz.",
            'Вместе посмотреть результат и показать, где он запутался.', 4),
           ("Xatoni o'zingiz tuzatib qo'yib, unga keyingi vazifani berasiz.",
            'Исправить ошибку самому и сразу дать ему следующую задачу.', 2),
           ("Unga to'g'ri namunani yuborib, solishtirib ko'rishini so'raysiz.",
            'Отправить ему правильный пример и попросить сравнить.', 3),
           ("Birinchi vazifasi bo'lgani uchun unga hozircha hech narsa demaysiz.",
            'Раз это его самая первая задача, пока ничего ему не говорить.', 1),
       ]),
    _s(63, "Jamoadoshingiz yordam so'ramaydi, lekin bitta vazifada bir necha kundan beri qotib qolgan.",
       'Коллега не просит помощи, но уже несколько дней стоит на одной задаче.', [
           ("So'ramayotgan ekan, o'zi baribir uddalab ketadi deysiz.",
            'Раз не просит, значит, сам справится — не трогать его.', 1),
           ("Undan qayerda qiyinchilik borligini to'g'ridan-to'g'ri so'raysiz.",
            'Прямо спросить, в чём именно у него сложность.', 4),
           ("Foydali bo'lishi mumkin bo'lgan havolani yuborib qo'yasiz.",
            'Отправить ссылку, которая может пригодиться.', 2),
           ("Vazifani birga ko'rib chiqish uchun unga vaqt taklif qilasiz.",
            'Предложить время, чтобы посмотреть задачу вместе.', 3),
       ]),
    _s(64, "Siz o'rgatgan usul jamoadoshga qiyin kelyapti, u o'zining sekinroq usulida ishlamoqchi.",
       'Способ, которому вы научили, даётся коллеге тяжело: он хочет работать своим, более медленным.', [
           ("Jamoada hamma bir xil usulda ishlashi kerakligini qat'iy aytasiz.",
            'Сказать, что в команде все обязаны работать одинаково.', 1),
           ("Usulni unga qadamma-qadam yana bir bor ko'rsatib berasiz.",
            'Ещё раз показать ему этот способ шаг за шагом.', 2),
           ("Ikkala usulni natija bo'yicha solishtirib, birga qaror qilasiz.",
            'Сравнить оба способа по результату и решить вместе.', 4),
           ("Hozircha unga o'zi xohlagan usulda ishlashiga ruxsat berasiz.",
            'Пока разрешить ему работать тем способом, каким он хочет.', 3),
       ]),
    _s(65, "Himoyada jamoadagi eng kuchsiz a'zoga so'z berish kerakmi degan savol tug'ildi.",
       'Возник вопрос: давать ли слово на защите самому слабому участнику команды.', [
           ("Unga o'zi yaxshi biladigan qismni berib, birga tayyorlanasiz.",
            'Дать ему часть, которую он знает лучше, и готовиться вместе.', 4),
           ("Xavf tug'dirmaslik uchun unga qisqa kirish qismini berasiz.",
            'Чтобы не рисковать, дать ему только короткое вступление.', 2),
           ("Undan qaysi qism haqida gapirishni xohlashini so'raysiz.",
            'Спросить у него, о какой части он хотел бы рассказать.', 3),
           ("Baho muhim bo'lgani uchun so'zni faqat kuchli a'zolarga berasiz.",
            'Раз оценка важна, слово дать только самым сильным участникам.', 1),
       ]),
    _s(66, "Yordam so'raganingizda jamoadoshingiz «bu oson, o'zing qilasan» deb javob berdi.",
       'В ответ на просьбу о помощи коллега сказал: «это просто, сам сделаешь».', [
           ("Uning bunday munosabati haqida yig'ilishda butun jamoaga aytasiz.",
            'Рассказать о таком его отношении всем на общей встрече.', 1),
           ("Boshqa a'zodan yoki ochiq manbalardan yordam izlab ko'rasiz.",
            'Поискать помощь у другого участника или в источниках.', 3),
           ("Qaysi qadamda qotib qolganingizni ko'rsatib, yana so'raysiz.",
            'Показать, на каком шаге вы застряли, и спросить ещё раз.', 4),
           ("Yordam so'ramay, ko'proq vaqt sarflab o'zingiz qilasiz.",
            'Не просить помощи и сделать самому, потратив больше времени.', 2),
       ]),
    _s(67, "Jamoaga ikki yangi a'zo bir vaqtda qo'shildi, sizda esa faqat bir kun bo'sh vaqt bor.",
       'В команду одновременно пришли двое новых, а у вас есть только один свободный день.', [
           ("Ikkalasiga ham hujjatlarni berib, savol bersa javob berasiz.",
            'Дать обоим документацию и отвечать на вопросы.', 2),
           ("Birinchisini o'rgatib, u ikkinchisiga o'rgatishini so'raysiz.",
            'Обучить первого и попросить его обучить второго.', 3),
           ("Ikkalasiga bir vaqtda kirish tushuntirishini o'tkazasiz.",
            'Провести вводное объяснение для обоих сразу.', 4),
           ("Birinchisi bilan shug'ullanib, ikkinchisini keyinga qoldirasiz.",
            'Заняться первым, а второго отложить на потом.', 1),
       ]),
    _s(68, "Jamoadoshingiz sizdan uy vazifasini ham o'rniga qilib berishni so'ramoqda.",
       'Коллега просит вас сделать за него ещё и домашнее задание.', [
           ("Munosabatingiz buzilmasligi uchun vazifasini o'zingiz qilib berasiz.",
            'Сделать задание за него, чтобы не портить отношения.', 1),
           ("Birga yechib ko'rishni taklif qilasiz, lekin o'rniga qilmaysiz.",
            'Предложить разобрать вместе, но не делать за него.', 4),
           ("O'z ishingiz ko'pligini sabab qilib, iltimosini rad etasiz.",
            'Отказать, сославшись на собственную загруженность.', 2),
           ("Qaysi mavzuni tushunmayotganini so'rab, o'shandan boshlaysiz.",
            'Спросить, какую тему он не понимает, и начать с неё.', 3),
       ]),
    _s(69, "Jamoada bir a'zo hamma narsani o'zi qilishga urinib, boshqalarga ish qoldirmayapti.",
       'Один участник пытается делать всё сам и не оставляет работы другим.', [
           ('Ish baribir bajarilayotgan ekan, hech narsaga aralashmaysiz.',
            'Раз работа всё равно делается, ни во что не вмешиваться.', 1),
           ("Undan qaysi vazifalarni boshqalarga bera olishini so'raysiz.",
            'Спросить у него, какие задачи он может передать другим.', 4),
           ('Uning tez orada charchab qolishi mumkinligini ogohlantirasiz.',
            'Предупредить, что он скоро может выгореть от такой нагрузки.', 2),
           ("Vazifalarni jamoa bilan ochiq qayta taqsimlashni taklif qilasiz.",
            'Предложить открыто перераспределить задачи вместе с командой.', 3),
       ]),
    _s(70, "Sizdan jamoaga yangi texnologiyani o'rgatish so'ralyapti, lekin siz ham uni endi o'rganyapsiz.",
       'Вас просят обучить команду новой технологии, но вы и сами только начали её осваивать.', [
           ("Darajangiz haqida gapirmasdan, o'rgatishga kirishib ketasiz.",
            'Не говоря ничего о своём уровне, взяться обучать остальных.', 1),
           ('Buni yaxshiroq biladigan boshqa odam topishni taklif qilasiz.',
            'Предложить найти другого человека, который знает это лучше.', 2),
           ("Darajangizni ochiq aytib, birga o'rganishni taklif qilasiz.",
            'Честно сказать о своём уровне и предложить учиться вместе.', 4),
           ("Avval o'zingiz kichik namuna qilib, keyin ko'rsatasiz.",
            'Сначала сделать небольшой пример самому, а потом показать.', 3),
       ]),
    # -- Yetakchilik va qaror / лидерство и решения ----------------------------------
    _s(71, "Siz sardorsiz. Jamoa rejangizga rozi bo'ldi, lekin hech kim birorta savol bermadi.",
       'Вы лидер. Команда согласилась с вашим планом, но никто не задал ни одного вопроса.', [
           ("Rejaning zaif joyini o'zingiz ko'rsatib, fikr so'raysiz.",
            'Самому назвать слабое место плана и спросить мнение.', 4),
           ("Har kimdan rejadagi o'z qismini aytib berishini so'raysiz.",
            'Попросить каждого рассказать свою часть плана.', 3),
           ("Savol bo'lmasa, ishni boshlashga buyruq berib qo'yasiz.",
            'Раз вопросов нет, дать команду начинать работу.', 2),
           ('Hamma tushungan deb hisoblab, ishni davom ettirasiz.',
            'Считать, что все всё поняли, и двигаться дальше по плану.', 1),
       ]),
    _s(72, "Siz sardorsiz va ikki a'zo bitta qiziq vazifani olishni xohlayapti.",
       'Вы лидер, и двое участников хотят взять одну и ту же интересную задачу.', [
           ("Kim olishini tanga tashlash yo'li bilan hal qilasiz.",
            'Решить подбрасыванием монеты, кто её возьмёт.', 1),
           ("Vazifani ikki qismga bo'lib, ikkalasiga ham ulush berasiz.",
            'Разделить задачу на две части и дать долю обоим.', 4),
           ("Tajribalirog'iga berib, ikkinchisiga keyingisini va'da qilasiz.",
            'Отдать более опытному, а второму пообещать следующую.', 2),
           ("Kim uchun bu vazifa ko'proq o'sish berishini hisobga olasiz.",
            'Учесть, кому эта задача даст больше роста.', 3),
       ]),
    _s(73, "Siz sardorsiz; jamoa a'zosi sizning qaroringizni ochiq shubha ostiga oldi.",
       'Вы лидер, и участник команды открыто поставил ваше решение под сомнение.', [
           ("Sardor sifatida qabul qilingan qaror o'zgarmasligini qat'iy aytasiz.",
            'Сказать как лидер, что принятое решение обсуждению не подлежит.', 1),
           ('Qaror nega aynan shunday qabul qilinganini batafsil tushuntirasiz.',
            'Подробно объяснить, почему решение принято именно таким.', 3),
           ("Uning dalillarini eshitib, kerak bo'lsa qarorni o'zgartirasiz.",
            'Выслушать его аргументы и при необходимости изменить решение.', 4),
           ("Muhokamani yig'ilish tugab, hamma tarqagandan keyinga qoldirasiz.",
            'Перенести обсуждение на время, когда встреча закончится.', 2),
       ]),
    _s(74, "Siz sardorsiz. Jamoa muddatga ulgurmasligi aniq bo'lib qoldi.",
       'Вы лидер. Стало очевидно, что команда не успевает к сроку.', [
           ('Eng oxirgi kungacha kutib turib, keyin hammaga xabar berasiz.',
            'Подождать до самого последнего дня и лишь потом сообщить об этом.', 1),
           ("Nimadan voz kechish mumkinligini aniqlab, o'qituvchiga aytasiz.",
            'Определить, чем можно пожертвовать, и сказать преподавателю.', 4),
           ("Qolgan vazifalarni qayta taqsimlab, eng muhimini oldinga olasiz.",
            'Перераспределить оставшиеся задачи и вывести вперёд главное.', 3),
           ("Hammadan bir necha kun qo'shimcha vaqt ishlashni so'raysiz.",
            'Попросить всех поработать дополнительно несколько дней.', 2),
       ]),
    _s(75, "Siz sardorsiz va bir a'zoni vazifadan chetlatish kerakmi degan savol ustida o'ylayapsiz.",
       'Вы лидер и думаете, не отстранить ли одного участника от задачи.', [
           ('Jamoa chatida uning ishi yaroqsiz ekanini ochiq aytasiz.',
            'Написать в общий чат, что его работа совсем не годится.', 1),
           ("Avval u bilan gaplashib, aniq kutilma va muddat belgilaysiz.",
            'Сначала поговорить с ним и обозначить ожидания и срок.', 4),
           ("Vazifani ogohlantirmasdan boshqa a'zoga o'tkazib yuborasiz.",
            'Передать задачу другому, не предупредив его об этом.', 2),
           ("Unga yordamchi biriktirib, ishni birga olib borishni taklif qilasiz.",
            'Приставить к нему помощника и вести работу вместе.', 3),
       ]),
    _s(76, "Siz sardorsiz; jamoa har bir mayda ish uchun ham sizdan ruxsat so'rayapti.",
       'Вы лидер, и команда спрашивает у вас разрешения даже по мелочам.', [
           ("Qaysi qarorlarni o'zlari qabul qila olishini aniq belgilab berasiz.",
            'Чётко определить, какие решения они могут принимать сами.', 4),
           ("So'rovlarga tez javob berib turib, ishni sekinlashtirmaysiz.",
            'Быстро отвечать на запросы, чтобы не тормозить работу.', 2),
           ("Bir necha bor «bu ishni o'zingiz hal qiling» deb javob berasiz.",
            'Несколько раз ответить: «решите этот вопрос сами».', 3),
           ('Bu sizga nazoratni saqlashga yordam beradi deb, shunday qoldiraverasiz.',
            'Оставить как есть — так вы сохраняете контроль над работой.', 1),
       ]),
    _s(77, "Siz sardorsiz. Ikki a'zo doim birga ishlaydi va jamoaning qolganidan uzilib qolgan.",
       'Вы лидер. Двое участников всё время работают вдвоём и оторвались от остальной команды.', [
           ('Ular samarali ishlayapti deb, hammasini shunday qoldirasiz.',
            'Раз они работают эффективно, оставить как есть.', 1),
           ("Vazifalarni aralash juftliklarda bajarishni joriy qilasiz.",
            'Ввести выполнение задач в смешанных парах.', 4),
           ("Ikkalasini ataylab turli vazifalarga ajratib qo'yasiz.",
            'Намеренно развести их по разным задачам.', 2),
           ("Ular qilgan ishni butun jamoaga ko'rsatishni so'raysiz.",
            'Попросить их показывать сделанное всей команде.', 3),
       ]),
    _s(78, "Siz sardorsiz va jamoada kayfiyat pasaygan: hamma charchagan, natija esa hali uzoq.",
       'Вы лидер, и в команде упал настрой: все устали, а результат ещё далеко.', [
           ("Muddat yaqinligini eslatib, harakatni oshirishni so'raysiz.",
            'Напомнить о сроке и попросить прибавить усилий.', 2),
           ("Kayfiyat o'tkinchi narsa deb hisoblab, rejaga umuman tegmaysiz.",
            'Считать, что настроение пройдёт, и вообще не менять план.', 1),
           ("Qilingan ishni ko'rsatib, keyingi qadamni kichik qilasiz.",
            'Показать сделанное и поставить следующий шаг небольшим.', 4),
           ("Jamoaga bir kun to'liq dam olishni taklif qilib ko'rasiz.",
            'Предложить команде взять один день полного отдыха.', 3),
       ]),
    _s(79, "Siz sardorsiz; o'qituvchi jamoa ishidan norozi ekanini sizga aytdi.",
       'Вы лидер, и преподаватель сказал вам, что недоволен работой команды.', [
           ("Kimning ishi yomonligini aniqlab, faqat o'shaning o'ziga aytasiz.",
            'Определить, чья именно работа плоха, и сказать об этом только ему.', 1),
           ('Tanqidni biroz yumshatib, jamoaga asosiy talablarni aytasiz.',
            'Немного смягчить критику и передать команде основные требования.', 3),
           ("Aniq nima yetishmayotganini so'rab, jamoaga to'liq yetkazasiz.",
            'Уточнить, чего именно не хватает, и полностью донести команде.', 4),
           ('Jamoani tushkunlikka solmaslik uchun buni hozircha aytmaysiz.',
            'Пока ничего не говорить, чтобы не подорвать настрой команды.', 2),
       ]),
    _s(80, "Siz sardorsiz. Jamoa g'alaba qozondi, mukofot esa faqat sizga taqdim etildi.",
       'Вы лидер. Команда победила, а награду вручили только вам.', [
           ("Sahnada har bir a'zoning hissasini nomma-nom aytasiz.",
            'На сцене поимённо назвать вклад каждого участника.', 4),
           ("Mukofotni jamoa bilan birga nishonlashni taklif qilasiz.",
            'Предложить отметить награду вместе с командой.', 3),
           ("Keyinroq jamoa chatida har bir a'zoga rahmat aytasiz.",
            'Позже поблагодарить каждого в общем чате команды.', 2),
           ('Mukofot sardorga berilishi odatiy hol deb, qabul qilasiz.',
            'Принять как обычное дело: награду всегда вручают лидеру.', 1),
       ]),
    # -- Adolat, e'tirof va halollik / справедливость, признание, честность ----------
    _s(81, "Jamoadoshingiz internetdan tayyor yechimni ko'chirib, o'zi yozgandek taqdim etmoqchi.",
       'Коллега хочет выдать скопированное из интернета готовое решение за своё.', [
           ("Vaqt kam qolganini hisobga olib, bunga ko'z yumib qo'ya qolasiz.",
            'Раз времени мало, закрыть на это глаза и ничего не говорить.', 1),
           ("Buni jamoaga aytib, manba ko'rsatilishi kerakligini bildirasiz.",
            'Сказать команде и обозначить, что источник нужно указать.', 4),
           ("Ko'chirilgan o'sha qismni o'zingiz qayta yozib chiqasiz.",
            'Самому переписать эту скопированную часть заново.', 2),
           ('U bilan alohida gaplashib, buning oqibatlarini tushuntirasiz.',
            'Поговорить с ним наедине и объяснить возможные последствия.', 3),
       ]),
    _s(82, "Jamoaning umumiy hisobotida sizning ismingiz tushib qolgan.",
       'В общем отчёте команды ваше имя оказалось пропущено.', [
           ("Hisobotni tayyorlagan a'zoga aytib, tuzatishni so'raysiz.",
            'Сказать тому, кто готовил отчёт, и попросить исправить.', 4),
           ('Hamma baribir biladi deb, bu haqda hech narsa demaysiz.',
            'Решить, что все и так это знают, и ничего не говорить.', 2),
           ("Bundan keyingi hisobotlarni o'zingiz yozishni talab qilasiz.",
            'Потребовать, чтобы все следующие отчёты писали только вы.', 1),
           ("O'qituvchiga o'z hissangiz haqida alohida yozasiz.",
            'Отдельно написать преподавателю о своём вкладе.', 3),
       ]),
    _s(83, "Deyarli hech narsa qilmagan a'zo taqdimotda asosiy so'zni olishni xohlayapti.",
       'Участник, который почти ничего не сделал, хочет взять на презентации главное слово.', [
           ("Ortiqcha bahs chiqmasligi uchun indamay rozi bo'la qolasiz.",
            'Согласиться без лишних споров с тем, что он предлагает.', 1),
           ('Taqdimot qismlarini kim nima qilganiga qarab taqsimlaysiz.',
            'Распределить части презентации по тому, кто что делал.', 4),
           ("Rozi bo'lasiz, lekin savollarga boshqalar javob berishini aytasiz.",
            'Согласиться, но сказать, что на вопросы отвечают другие.', 2),
           ("Undan taqdimotda qaysi qism haqida gapira olishini so'raysiz.",
            'Спросить у него, о какой части он сможет рассказать.', 3),
       ]),
    _s(84, "Jamoadoshingiz kasal bo'lib, o'z qismini tugata olmadi, baho esa umumiy qo'yiladi.",
       'Коллега заболел и не доделал свою часть, а оценка ставится общая.', [
           ("Qolgan qismni jamoa bilan bo'lib, holatni o'qituvchiga aytasiz.",
            'Разделить остаток с командой и сообщить преподавателю.', 4),
           ("Uning qismini o'zingiz tugatib qo'yib, buni jamoaga aytasiz.",
            'Доделать его часть самому и сказать об этом команде.', 3),
           ("Hisobotda uning kasal bo'lganini sabab qilib ko'rsatasiz.",
            'Указать в отчёте его болезнь как причину незавершённости.', 2),
           ("Kasal bo'lgani uchun uning ismini ro'yxatdan chiqarib tashlaysiz.",
            'Убрать его имя из списка авторов, раз он всё равно болел.', 1),
       ]),
    _s(85, "Sizga jamoadoshingizning shaxsiy muammosi haqida ishonch bilan aytishdi.",
       'Вам по секрету рассказали о личной проблеме вашего коллеги.', [
           ("Jamoaga aytib qo'yasiz — shunda hamma a'zo sababini bilib oladi.",
            'Рассказать всей команде — пусть все знают настоящую причину.', 1),
           ("Sirni saqlab, unga qanday yordam kerakligini o'zidan so'raysiz.",
            'Сохранить это в тайне и спросить у него, нужна ли помощь.', 4),
           ("Jamoa tushunib munosabatda bo'lishi uchun sardorga aytasiz.",
            'Рассказать лидеру, чтобы команда отнеслась с пониманием.', 2),
           ("Uning yuklamasini sababini aytmay kamaytirishni taklif qilasiz.",
            'Предложить снизить его нагрузку, не называя причину.', 3),
       ]),
    _s(86, "Ishni kam qilgan a'zo baho taqsimotida teng ulush talab qilmoqda.",
       'Участник, сделавший мало, требует равной доли при распределении оценки.', [
           ("Kim nima qilganini birga yozib chiqib, shunga qarab bo'lasiz.",
            'Вместе выписать, кто что сделал, и договориться по этому.', 4),
           ("Nizo chiqmasligi uchun teng taqsimlashga rozi bo'lasiz.",
            'Согласиться на равное деление, чтобы не было конфликта.', 2),
           ('Uni jamoa chatida hamma oldida ochiqdan-ochiq ayblab chiqasiz.',
            'Открыто обвинить его при всех в общем чате и потребовать объяснений.', 1),
           ("Qaror qabul qilishni butunlay o'qituvchiga havola qilasiz.",
            'Полностью передать решение этого вопроса преподавателю.', 3),
       ]),
    _s(87, "Do'stingiz bilan bitta jamoadasiz va u sizdan o'z kechikishini yashirishni so'rayapti.",
       'Вы в одной команде с другом, и он просит скрыть его отставание.', [
           ("Do'stligingizni o'ylab, uning kechikishini jamoadan yashirasiz.",
            'Ради дружбы скрыть его отставание от остальной команды.', 1),
           ("Yashira olmasligingizni aytib, o'zi aytishini taklif qilasiz.",
            'Сказать, что скрыть не сможете, и предложить сказать самому.', 4),
           ("Bir marta yashirib, keyingi safar aytishini shart qilasiz.",
            'Один раз скрыть, но поставить условие: в следующий раз говорить.', 2),
           ('Unga kechikishni tezroq yopib olish uchun yordam berasiz.',
            'Помочь ему поскорее закрыть это отставание по работе.', 3),
       ]),
    _s(88, "Jamoa ishni bo'lishdi, lekin sizga eng zerikarli qismlar tushdi.",
       'Команда разделила работу, но вам достались самые скучные части.', [
           ("Zerikarli qismni tezda bajarib olib, boshqa qiziq ishga o'tasiz.",
            'Быстро сделать скучную часть и переключиться на интересную.', 2),
           ("Norozi ekaningizni ochiq aytmay, ishni sekinlashtirib bildirib qo'yasiz.",
            'Не говоря ничего прямо, показать недовольство, замедлив всю работу.', 1),
           ("Taqsimot qanday tuzilganini so'rab, qayta ko'rishni taklif qilasiz.",
            'Спросить, как составлялось распределение, и предложить пересмотреть.', 4),
           ("Qismingizni bajarib, keyingi taqsimotda almashishni kelishasiz.",
            'Выполнить свою часть и договориться поменяться в следующий раз.', 3),
       ]),
    _s(89, "Jamoadoshingiz imtihon paytida sizdan yordam so'rayapti, bu esa qoidaga zid.",
       'Во время экзамена коллега просит у вас помощи, хотя это против правил.', [
           ('Jamoadoshlik yuzasidan unga imkon boricha yordam berib yuborasiz.',
            'Помочь ему по-товарищески настолько, насколько это возможно.', 1),
           ("Rad etib, imtihondan keyin birga tayyorlanishni taklif qilasiz.",
            'Отказать и предложить подготовиться вместе после экзамена.', 4),
           ("Uning so'ragani haqida o'qituvchiga darhol xabar berasiz.",
            'Сразу сообщить преподавателю о том, что он просил помощи.', 2),
           ('Bu qoidaga zid ekanini eslatib, savoliga javob bermaysiz.',
            'Напомнить, что это против правил, и не отвечать ему.', 3),
       ]),
    _s(90, "Jamoada bir a'zo boshqalar haqida ularning orqasidan gapiradi.",
       'Один участник говорит об остальных за их спиной.', [
           ('Indamay tinglab turasiz va bunga hech qanday javob qaytarmaysiz.',
            'Молча слушать эти разговоры и никак на них не реагировать.', 1),
           ("Eshitganingizni keyinroq o'sha odamning o'ziga yetkazasiz.",
            'Позже передать услышанное самому этому человеку.', 2),
           ("Suhbatni to'xtatib, gapni o'sha odamga aytishni taklif qilasiz.",
            'Остановить разговор и предложить сказать это ему лично.', 4),
           ("Bunday suhbatlarga umuman qo'shilmasligingizni ochiq aytasiz.",
            'Сказать, что вы в таких разговорах вообще не участвуете.', 3),
       ]),
    # -- Bosim, muddat va o'zgarish / давление, сроки и изменения --------------------
    _s(91, "Loyihaning yarmida o'qituvchi talablarni o'zgartirdi, jamoa esa esankirab qoldi.",
       'В середине проекта преподаватель изменил требования, и команда растерялась.', [
           ("Nima o'zgarganini ro'yxat qilib, qaysi ish saqlanishini aniqlaysiz.",
            'Составить список изменений и понять, какая работа остаётся.', 4),
           ("Bunday o'zgarish adolatsiz ekanini aytib, ochiq e'tiroz bildirib chiqasiz.",
            'Заявить открытый протест: такое изменение просто несправедливо.', 1),
           ("O'qituvchidan o'zgarishlarni yozma aniqlashtirishni so'raysiz.",
            'Попросить преподавателя письменно уточнить изменения.', 3),
           ("Eski reja bo'yicha davom etib, oxirida hammasini moslashtirasiz.",
            'Продолжать по старому плану, а в конце всё подогнать.', 2),
       ]),
    _s(92, "Muddatga bir kun qolganda jamoa tayyor ishning bir qismini yo'qotib qo'ydi.",
       'За день до срока команда потеряла часть уже готовой работы.', [
           ("Avvalo kim yo'qotib qo'yganini aniqlashga kirishasiz.",
            'Первым делом начать выяснять, кто именно это потерял.', 2),
           ("Eski nusxalar bor-yo'qligini hammadan so'rab chiqasiz.",
            'Спросить у всех, не осталось ли у кого-нибудь старых копий.', 3),
           ("Kim tezroq tiklay olishini aniqlab, ishni darhol boshlaysiz.",
            'Определить, кто быстрее восстановит, и сразу начать работу.', 4),
           ("Muddatni uzaytirishni so'rashdan boshqa chora qolmadi deysiz.",
            'Сказать, что теперь не остаётся ничего, кроме переноса срока.', 1),
       ]),
    _s(93, "Jamoa tunda ishlashni odat qilgan, siz esa bunday rejimda ishlay olmaysiz.",
       'Команда привыкла работать ночью, а вы в таком режиме работать не можете.', [
           ("Tunda o'tgan muhokamalarni har safar o'tkazib yuboraverasiz.",
            'Каждый раз пропускать обсуждения, которые прошли ночью.', 1),
           ("Jamoaga rejimingizni aytib, umumiy ish vaqtini kelishasiz.",
            'Сказать команде о своём режиме и согласовать общее рабочее время.', 4),
           ("Jamoaga moslashib, siz ham tunda ishlashga urinib ko'rasiz.",
            'Подстроиться под команду и тоже пробовать работать ночью.', 2),
           ("Kunduzi ko'proq ishlab, tunda faqat muhim paytda qo'shilasiz.",
            'Больше работать днём, а ночью подключаться только в важные моменты.', 3),
       ]),
    _s(94, "Kutilmaganda jamoadagi ikki a'zo bir vaqtda loyihadan chiqib ketdi.",
       'Неожиданно двое участников одновременно вышли из проекта.', [
           ("Qolgan ishni qayta baholab, eng muhimini oldinga qo'yasiz.",
            'Пересмотреть оставшуюся работу и поставить главное вперёд.', 4),
           ("Ularning ishini qolganlar o'rtasida teng bo'lishni taklif qilasiz.",
            'Предложить поделить их работу между оставшимися поровну.', 2),
           ("O'qituvchidan yangi a'zo yoki qo'shimcha vaqt berishni so'raysiz.",
            'Попросить у преподавателя нового участника или дополнительное время.', 3),
           ("Ularni loyihaga qaytishga ko'ndirish uchun ancha vaqt sarflaysiz.",
            'Потратить много времени на уговоры вернуться в проект.', 1),
       ]),
    _s(95, "Muhim taqdimotdan oldin jihoz ishlamay qoldi va jamoa vahimaga tushdi.",
       'Перед важной презентацией отказало оборудование, и команда запаниковала.', [
           ("Jihozni kim tayyorlagan bo'lsa, o'shani hamma oldida ayblaysiz.",
            'Обвинить при всех того, кто отвечал за подготовку оборудования.', 1),
           ("Kimga nima vazifa ekanini aytib, zaxira variantga o'tasiz.",
            'Распределить, кто что делает, и перейти на запасной вариант.', 4),
           ("Taqdimotni keyinroqqa kechiktirishni so'rab ko'rasiz.",
            'Попробовать попросить перенести презентацию на позже.', 2),
           ("Tinchlanishga chaqirib, muammoni hal qilishga kirishasiz.",
            'Призвать успокоиться и заняться решением проблемы.', 3),
       ]),
    _s(96, "Jamoa hafta davomida qattiq ishladi, lekin natija kutilganidan ancha past chiqdi.",
       'Команда всю неделю усердно работала, но результат вышел заметно хуже ожидаемого.', [
           ("Nima ishlamaganini birga tahlil qilib, xulosani yozib qo'yasiz.",
            'Вместе разобрать, что не сработало, и записать выводы.', 4),
           ("Keyingi safar ko'proq ishlash kerakligini jamoaga aytasiz.",
            'Сказать, что в следующий раз нужно работать больше.', 2),
           ("Jamoani qilingan katta mehnat uchun qo'llab-quvvatlaysiz.",
            'Поддержать команду за проделанный большой труд.', 3),
           ("Natija haqida umuman gapirmasdan, darhol yangi vazifaga o'tasiz.",
            'Не обсуждать результат вовсе и сразу перейти к новой задаче.', 1),
       ]),
    _s(97, "Muddat yaqin va jamoa sifatni pasaytirib bo'lsa ham topshirishga qaror qildi.",
       'Срок близко, и команда решила сдать работу, даже пожертвовав качеством.', [
           ("Qaysi joylarda sifat pasayganini yozib qo'yib, topshirasiz.",
            'Записать, где именно снижено качество, и сдать.', 4),
           ("O'z qismingizni sifatli qilib, qolganiga umuman aralashmaysiz.",
            'Сделать качественно свою часть и не лезть в остальное.', 1),
           ("Eng muhim qismni sifatli qoldirishni taklif qilasiz.",
            'Предложить сохранить качество хотя бы в главной части.', 3),
           ("Qarorga qo'shilasiz va hech narsani yozib qo'ymaysiz.",
            'Согласиться с решением и ничего вообще не фиксировать.', 2),
       ]),
    _s(98, "Jamoa ikki kun ishlagan yo'nalish noto'g'ri ekanini tushunib qoldingiz.",
       'Вы поняли, что направление, над которым команда работает два дня, выбрано неверно.', [
           ("Jamoaning o'zi buni sezib qolishini kutib turasiz.",
            'Подождать, пока команда сама заметит это со временем.', 1),
           ("Ikki kunlik mehnat behuda ketmasin deb, davom etasiz.",
            'Чтобы два дня труда не пропали, продолжить.', 2),
           ("Buni darhol aytib, dalillaringizni jamoaga ko'rsatasiz.",
            'Сразу сказать об этом и показать команде свои доводы.', 4),
           ("Yangi yo'nalish bo'yicha kichik namuna qilib, keyin taklif qilasiz.",
            'Сделать небольшой пример нового направления и потом предложить.', 3),
       ]),
    _s(99, "Bitiruv loyihasida jamoadoshingiz boshqa kursga o'tib ketdi va aloqaga chiqmayapti.",
       'В выпускном проекте коллега перевёлся на другой курс и не выходит на связь.', [
           ("Uning qismini jamoa va o'qituvchi bilan qayta rejalashtirasiz.",
            'Определить его часть и перепланировать её с преподавателем.', 4),
           ("U baribir qaytib keladi deb, uning qismini kutib o'tiraverasiz.",
            'Продолжать ждать его часть, рассчитывая, что он всё-таки вернётся.', 1),
           ("U bilan bog'lanishning boshqa yo'llarini sinab ko'rasiz.",
            'Попробовать другие способы связаться с ним ещё раз.', 3),
           ("Uning qismini hozircha chetga surib, boshqa ishlarni qilasiz.",
            'Пока отложить его часть в сторону и заняться другим.', 2),
       ]),
    _s(100, "Loyiha tugadi; o'qituvchi jamoa a'zolaridan bir-birini baholashni so'radi.",
       'Проект завершён, и преподаватель попросил участников оценить друг друга.', [
           ("Hech kimni ranjitmaslik uchun hammaga bir xil yuqori baho qo'yasiz.",
            'Поставить всем одинаково высокие оценки без разбора.', 2),
           ("Har bir a'zoga aniq misollar bilan kuchli va zaif tomonini yozasiz.",
            'Написать каждому сильную и слабую сторону с примерами.', 4),
           ("Baholashni umuman o'tkazib yuborasiz — bu faqat munosabatlarni buzadi.",
            'Пропустить оценивание совсем — оно только портит отношения.', 1),
           ('Faqat kuchli tomonlarini yozib, zaif tomonlarini yozmaysiz.',
            'Написать только сильные стороны, не указывая слабых.', 3),
       ]),
]
